### ISSUE TITLE
Getting registration failure while creating an app inside Dev Center

### ISSUE THREAD

**Issue by harshlal-chetu** [virencehealth/apiserver.virencehealth.com#100]
While creating Application, on submit the details, we are getting the below error.
"Registration Failure
Your registration was unsuccessful"
![image](https://user-images.githubusercontent.com/19240241/73011150-b214ff80-3e39-11ea-9892-6cf51c9452af.png)

**Comment by KedarGanta** [comment]
Are you trying to access the portal and complete registration from outside US?

**Comment by KedarGanta** [comment]
@harshlal-chetu  Are you trying to access the portal and complete registration from outside US?

**Comment by harshlal-chetu** [comment]
Hi Kedar,

Thank you for quick reply!
Yes, we are trying to access the portal outside US and successfully registered on Developer Portal. But we are not able to create the app inside Dev Center to generate client ID and secret for API connection.

Is it not allowed to create the app inside Dev Center because of aforementioned reason?
If yes, can we create the app in US and then utilize this same app in India to generate access token and then proceed with our development needs, outside US?

Please let us know, it is urgent.

Thank you,
Harsh

**Comment by KedarGanta** [comment]
@harshlal-chetu  yes, you can create the app entry in US and use the client credentials for your development in India...

**Comment by harshlal-chetu** [comment]
Thank you so much for the update!
