### ISSUE TITLE
Novo 2.0 project - CHC//Novo - issues updating certain Race/Ethnicity Values via a PUT /patient

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#101]
**Describe the bug**
We're not able to update Race or Ethnicity for "Patient Declined", or similar values.  Updating with a code of "2138-6" and display of "Andalusian" seems to wor fine.

**To Reproduce**
Perform the PUT /patient with the following - and the race isn't updated.
"resource": 
         "resourceType": "Patient",
         "id": "1889775163729800",
         "extension": [
            {
               "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
               "valueCodeableConcept": {
                  "coding": [
                     {
                        "system": "http://www.gehealthcare.com/fhir/cpsemr/codesystem/RACE",
                        "code": "declined",
                        "display": "Patient Declined"
                     }
                  ]
               }
            },

I realize that I'm sending in a different system than the FHIR standards - "http://hl7.org/fhir/v3/Race",

But I'm trying to match the system based on what comes out for the same code/display via a GET /Patient.  When I perform a GET, I receive the same output as above.

**Expected behavior**
Race/Ethnicity should update on the chart.

**Comment by Torin-Shepard-athena** [comment]
This behavior can happen when there are missing or incorrect HL7 Code values configured for Registration > Race items in CPS Administration.

This may be a configuration issue.  Please check values for "HL7 Code" in CPS Administration > Orange folders > Registration > Race.  These values should match the corresponding RACE entries in API Server mappings.properties file.

Remember to restart Interop JBoss Server to ensure API Server reads the new values.

![Screenshot CPS Admin Race Mappings](https://user-images.githubusercontent.com/52474202/74196525-4b059200-4c12-11ea-8a52-df999dcfd8d1.png)

**Comment by Torin-Shepard-athena** [comment]
Updates to HL7 Code values for items in the Race list were completed at CHC on February 14.
