### ISSUE TITLE
Novo 2.0 project - CHC//Novo - Updates to Patients via the GE API don't appear to trigger outbound HL7 messages to other external systems

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#102]
**Putting this ticket in on behalf of Lori Rozanski, and Nicholas Ciaburri at Community Health.

**Describe the bug**
Updates to Patients via the GE API don't appear to trigger outbound HL7 messages to other external systems

**To Reproduce**
PUT updates on patients.

**Expected behavior**
Doesn't appear to trigger an HL7 message at the CHC site.

**Comment by andylebo** [comment]
After a bit more testing - it looks like changes over the API do not appear to be showing in the Centricity Activity Logs either.

**Comment by andylebo** [comment]
Torin Shepard - 2.11.2020 via phone call

Creation of a patient generates an update event, but an update does not. Goes back to a design decision 11 years ago.  MIK was designed to use DB triggers -> Have to be in the UI touching demographics, and/or insurance to trigger the MIK event.

This is going to require a development from the GE/Athena side of things.

**Comment by andylebo** [comment]
Still an outstanding question for POST or PUT of /Appointments

**Comment by Amits2070** [comment]
This is a kind enhancement.A new bug has been created for same. It will be addressed in future release.
