### ISSUE TITLE
Novo 2.0 project - CHC//Novo - GET /Appointments endpoint doesn't support a cancel reason

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#103]
**Describe the bug**
It would be great if the /Appointments endpoint sent out the Cancel Reason for an appointment.

For example - 
![image](https://user-images.githubusercontent.com/20426558/73487890-7adcac00-436d-11ea-843c-f34fbb420883.png)

**To Reproduce**
Cancel and appointment then hit the /Appointments endpoint for the appointment.  This information doesn't come out over the API.

**Comment by andylebo** [comment]
Should be fixed in the 2020 version -

**Comment by Rinkal-jain** [comment]
Cancel Reason is not currently supported; Cancel reason can be indicated in the  Appointment Notes field
