### ISSUE TITLE
Account and $PostPayment call filtering by BillStatus

### ISSUE THREAD

**Issue by shayes-phreesia** [virencehealth/apiserver.virencehealth.com#104]
Currently when reading a Patient account the api is filtering by bill status. Currently, no tickets are returned in a bill status of "New." All other bill statuses including "In Progress" return account responses even if there are no procedures.  This results in being unable to post a payment to said New tickets. Payments taken for a copay or visit charge. then post to the the wrong ticket or fail to post at all if the only ticket is in a New status. According to API documentation we should be able to read any visit with an assigned ticket number in Account response. 

This is affecting several live customers. 

**To Reproduce**
1. Schedule a visit for today in the system
2. Generate superbill - assigning ticket no 
3. Try to query accounts - this visit id/ticket no will not be returned but any other tickets will be
4. Collect a payment - this will post to the wrong ticket.

**Expected behavior**
We should be able to read all tickets regardless of bill status as long as it is a valid visit id/ticket no combination in the system.

Version 12.3 SP3

**Comment by shayes-phreesia** [comment]
any update?

**Comment by shayes-phreesia** [comment]
any update?

**Comment by rashmi1977** [comment]
This is not yet supported. It will be addressed future release.

**Comment by Amits2070** [comment]
As this is new development. Bug has been created in jira for same .Closing this issue for now.

**Comment by shayes-phreesia** [comment]
Hi @Amits2070 @rashmi1977  you mentioned it "new development" is it slotted for a particular release?

**Comment by shayes-phreesia** [comment]
when is this planned for release @Amits2070  @rashmi1977

**Comment by shayes-phreesia** [comment]
is it possible to get any update on this @Amits2070  @rashmi1977
