### ISSUE TITLE
Is there an API or documentation that defines the valid ValueSets by [id]?

### ISSUE THREAD

**Issue by redshirtrob** [virencehealth/apiserver.virencehealth.com#105]
How can I get a list of all ValueSets?

I'd like to be able to get information on valid appointment types, appointment reasons, etc... I saw the following question, which somewhat addresses the appointment types:

https://github.com/virencehealth/apiserver.virencehealth.com/issues/19

However, I cannot find any documentation that calls out `C80APPOINTMENTTYPECPS` as something I would search against.

**Comment by Torin-Shepard-athena** [comment]
ValueSet resources can be enumerated by retrieving the fhir/List resource with an id of ValueSet
GET [base]/fhir/List/ValueSet

**Comment by redshirtrob** [comment]
I get a 403 Not Authorized. Is there a specific scope I need to use?

**Comment by Torin-Shepard-athena** [comment]
user/ValueSet.read

**Comment by redshirtrob** [comment]
That's not it. I already have user/*.* in the scopes. It must be something else.

**Comment by Torin-Shepard-athena** [comment]
Please try again after a change was made to the configuration of cpsapisandbox.

**Comment by redshirtrob** [comment]
Thanks, that works now.
