### ISSUE TITLE
Is there any recent data in the developer sandbox for slots/schedules/appointments?

### ISSUE THREAD

**Issue by redshirtrob** [virencehealth/apiserver.virencehealth.com#106]
Is there any recent data in the developer sandbox for slots, schedules, and appointments?

When I query for slots, the newest data I get is from 2009-07-25. Similarly when I query the schedules I get data that starts and ends around 2007-2008.

Am I missing something? I would expect current data for testing.

**Comment by nkadmane** [comment]
We have developed an utility which will add a schedule and slots for patient **Walter Caldwell** and one appointment will be booked for one of the slot.
Slots of duration 30 mins will get created from time
slot.startTime=09:00:00
slot.endTime=17:00:00

Appointment will be booked for slot time 9:00 to 9:30.

This utility will be executed every midnight and schedule, slots and appointment will be created for the next day.

Now we will always get appointment data for future date and empty slots from future date will be available for patient **Walter Caldwell** to create appointments through API if needed.
