### ISSUE TITLE
OAuth refresh tokens don't work after the access token expires on the Demo API Server

### ISSUE THREAD

**Issue by redshirtrob** [virencehealth/apiserver.virencehealth.com#107]
**Describe the bug**
I cannot use the refresh token to obtain a new access token if I let the access token expire.

**To Reproduce**
1. Obtain an access token from the demo server using the OAuth flow. Use the Practitioner account credentials. Specify "offline_access" in the scope.
2. Wait just over one hour for the access token to expire.
3. Attempt to get a new access token using the refresh token from step 1.
4. Observe the following response:
```
{
    "expires_in":0,
    "error":"invalid_client","error_description":"Refresh token could not be mapped to the original authorization request. User must re-authenticate."
}
```

**Expected behavior**
I expect a new access token and refresh token.

**Additional context**
If I attempt a refresh prior to the access token's expiration, the refresh flow works. It's only when the current access token expires that I run into trouble. But, this is all but guaranteed to happen in a production environment.

**Comment by ychowdhary** [comment]
Thanks for posting the issue.This is a known behavior and we will consider this in our future planning.
