### ISSUE TITLE
Getting the Sample Provider Authorized for these endpoints:

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#109]
We've been working with your APIs for several months now and are ready to being stringing the calls together for our workflow.  We are getting a "Unauthorized" response when we try to make a request to the following endpoints for the sample provider listed in the documentation.  

We have followed the steps and are able to generate the token, however, we are not able to successfully use that token in these calls.  Can you please help?

How do we get the sample provider authorized for https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Location? 

How do we get the sample provider authorized for https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Medication/? 

How do we get the sample provider authorized for https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/MedicationAdministration/?

**Comment by Torin-Shepard-athena** [comment]
The sample calls to authorize endpoint listed in [AP Access Documentation](https://mydata.athenahealth.com/access-centricity-apis) specify OAuth2 scopes for only patient/*.read.

This page includes the following note.  The sample call to the authorize endpoint requests an access token for a specific patient context by specifying the OAuth2 scopes for patient context (patient/*.read and launch/patient). These scopes will prompt you to select a patient. If you do not want to establish a patient context with your access token, then you may use other scopes that are available as part of the [SMART®](http://smarthealthit.org/) on [FHIR®](http://wiki.hl7.org/index.php?title=FHIR) standard.

[SMART App Launch: Scopes and Launch Context](http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html) describes the supported scopes.

You can use user scopes for the sample provider to get access to system resources and to access multiple patients.
[API Resources](https://mydata.athenahealth.com/fhirapidoc) lists the groupings of system, clinical, and practice management resource types.

The current CPS API Sandbox database has patients with MedicationStatement and the referenced Medication resources but does not have MedicationAdministration sample data.

**Comment by developer1254** [comment]
Hi Torin, 

When I'm hitting the 'Medication', 'MedicationAdministration', or 'Location' endpoints I'm receiving the the response below. Can you confirm for test provider 'hwinston@sboxprovtenant.com' that it has access to the above endpoints?

![image](https://user-images.githubusercontent.com/61989961/76456779-93e16f80-63a5-11ea-8dfd-7dceef9978be.png)

**Comment by Torin-Shepard-athena** [comment]
Yes.  This sample work account is authorized for these resource types.  It is important to have correct parameter values in the URL to the authorize endpoint.  Please check what scope is passed in your authorize request.  In The token endpoint response that has the access token should also have the granted scopes.

**Comment by developer1254** [comment]
Hi Torin, 

Thanks for your response, I'll take a look at the parameters being passed. 

Can you confirm the sandbox API is still active? I'm getting a non-response message from all my calls now. I opened another issue(126) this morning regarding the patient search. This might be related.

**Comment by jdmaple** [comment]
Thank you Torin-  we were able to resolve this issue with your help.

**Comment by healthbanksdev** [comment]
Hi, could you share your resolution to this issue?  I am experiencing the same thing.  I am using an authorization scope of user/*.* and receiving a token just fine, but I'm then receiving Forbidden/Not Authorized responses to any endpoints that I'm calling.
