### ISSUE TITLE
Test Providers

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#111]
Is there a better Practitioner that we should utilize in queries when trying to locate items? Again the issue here is in string API calls together.  We are having trouble stringing multiple calls together and returning complete data for a single provider.  The test provider does not seem to return consistent (if any) information.

**Comment by ychowdhary** [comment]
@jdmaple Can you provide us with more information to exactly what you are trying to achieve.It will help us in giving you better answer.

**Comment by jdmaple** [comment]
We figured out the issue on our side.  Thank you for your help.
