### ISSUE TITLE
Subscriber call - Insurance Information

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#112]
On the subscriber call, how do we get insurance information for a dependent/child?

**Comment by Torin-Shepard-athena** [comment]
Please clarify the question.  What resource type is meant by "Subscriber call"?

Coverage resource can be searched by subscriber which is a reference to a Patient resource.

If you have Patient.id for a dependent/child, you can get the insurance coverage for that Patient.

**Comment by jdmaple** [comment]
Thanks for clarifying Torin, this helped our team figure out what to do.  We are able to get the coverage information required.
