### ISSUE TITLE
Appointment Call

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#113]
On the appointment call, we found an example that has  '_include=Appointment:patient' in the URL.  However, we couldn't not find this documented?  Can you clarify why this was added and what other parameters are available with this call?

When we update, what fields are we allowed (required & optional) to update through the API?

**Comment by Torin-Shepard-athena** [comment]
CPS API Server supports the basic mechanism for the FHIR search result parameter _include as described at https://www.hl7.org/fhir/dstu2/search.html#include.

Appointment?searchparams&_include-Appointment:patient will return a Bundle which includes appointments that match searchparams and the Patient resources references by those appointments.  This is a feature of FHIR APIs that reduces the total number of API calls required to get all desired resources.

The modifier:recurse is not supported for _include.
Although you can use _include to have CPS FHIR Server add the Patients to the Bundle of Appointments, you cannot _include resources that are referenced by the Patient.  That requires additional FHIR queries.

**Comment by jdmaple** [comment]
This was helpful, thank you for clarifying the parameters.  We are able to retrieve appointments.
