### ISSUE TITLE
Looking up Dictionary Values

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#115]
How do we get dictionaries for identifier values we'll find in other calls? We located the below example in another issue/resolutions, but how would we know these are the identifiers to pass in? What other ones are there and where can we find them? 

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/ValueSet/C80APPOINTMENTTYPECPS 

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/ValueSet/C80APPOINTMENTTYPEEMR

**Comment by Torin-Shepard-athena** [comment]
https://github.com/virencehealth/apiserver.virencehealth.com/issues/105
API or documentation that defines the valid ValueSets by [id]
ValueSet resources can be enumerated by retrieving the fhir/List resource with an id of ValueSet
GET [base]/fhir/List/ValueSet

**Comment by jdmaple** [comment]
We did see issue #105 and tried what you suggested.  We are still receiving a Not Authorized Response (attached)
![provider not authorized](https://user-images.githubusercontent.com/29407584/75805698-8a219180-5d3f-11ea-80c4-520ed57dc4a0.png)

**Comment by Torin-Shepard-athena** [comment]
Please confirm if you have also followed comment posted at [Issue #109](https://github.com/virencehealth/apiserver.virencehealth.com/issues/109) to get access token with user scope and no specific patient context.  user/ValueSet.read scope must be listed in the scope returned along with accessToken.

**Comment by jdmaple** [comment]
@Torin-Shepard-athena  - we believe we are following the correct process to get the access token as described in #109 What can we provide for your review to help push this issue towards resolution?

**Comment by Torin-Shepard-athena** [comment]
We may need to see the exact URL you are using to get authorization code.

The following process works for me.

Get auth code from API Server authorize endpoint
- [https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&**scope**=openid%20profile%20**user/*.read**%20offline_access&response_type=code%20id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fanything&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=myClientId](https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20user/*.read%20offline_access&response_type=code%20id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fanything&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=myClientId)
- Sign in as hwinston@sboxprovtenant.com
- https://httpbin.org/anything displays auth code in $.form.code

Post this auth code to API Server token endpoint
- https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token
- Authorization header Basic Auth myClientId:myClientSecrect
- Request Body includes code=auth_code
- On success, token endpoint returns access_token and several other elements
- scope includes user/ValueSet.read, user/Organization.read, and read scopes for other System resource types

Get requests with Authorization header set to "Bearer access_token"
- https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/List/ValueSet
- https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/ValueSet/C80APPOINTMENTTYPECPS
- https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Organization?_count=300

**Comment by jdmaple** [comment]
Thanks Torin!  We are now able to get responses from these endpoints.

Question on the Authorization piece - is there a way to programmatically generate the token?  Our app has a back-end process that will run headless against the API.  Usually, this runs under a service account and is scheduled instead of initiated by a user interaction (like a button click).

**Comment by Torin-Shepard-athena** [comment]
https://github.com/virencehealth/apiserver.virencehealth.com/tree/master/token-generation-sample-code

**Comment by jdmaple** [comment]
Our team is using this code however, it still requires a manual login into the  provider’s account. Is there a way to complete that step programmatically?



In response to COVID-19 we have adjusted our staff to work remotely. We will continue to support our clients and apps and expect no disruptions in service.

Thanks,
Jonathan



[cid:ezgif.com-resize(1)_e5afbe4f-d464-4368-8459-5f27d4e84448.png]      Jonathan Maple
Tel. 505-303-1668
Mobile (Emergency): 505-750-3317
Fax 773-435-6673
www.bytesizedsolutions.com<http://www.bytesizedsolutions.com/>

**Comment by jdmaple** [comment]
@Torin-Shepard-athena following up on this question.  Our process is headless and needs to run on a nightly basis.  Is there a way to obtain the token without manually logging in as hwinston@sboxprovtenant.com?

**Comment by jdmaple** [comment]
@Torin-Shepard-athena  Following up on our question, is there a way for us to authenticate and consume these APIs using a headless process?

**Comment by Torin-Shepard-athena** [comment]
@jdmaple Please go to [API Resources](https://mydata.athenahealth.com/fhirapidoc) and click on Security to learn more about the authorization services/flows and options.  If you need more information, you can send email to athenaInterop@athenahealth.com.

**Comment by KedarGanta** [comment]
@jdmaple  I would assume that your question has been addressed. Please open a new issue if you need additional help.
