### ISSUE TITLE
Organization Resource

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#116]
Why doesn't https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Organization/ work like the practitioners call and return a list of organizations? We receive a:

<td>Not authorized</td> response. How do we get the sample provider authorized for this resource?

**Comment by Torin-Shepard-athena** [comment]
Please see comments posted for Issue [Issue #109 ](https://github.com/virencehealth/apiserver.virencehealth.com/issues/109)

**Comment by jdmaple** [comment]
@Torin-Shepard-athena we are still experiencing authorization issues with this call (and with Issue #115 )  What can we provide to help troubleshoot?

**Comment by jdmaple** [comment]
Thank you @Torin-Shepard-athena .  We've worked through the Authorization issues and are getting the expected responses.
