### ISSUE TITLE
Medication Statements

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#117]
Can you please provide some patient IDs that have a medications statement?  https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/MedicationStatement?patient=1442678381200620

**Comment by jdmaple** [comment]
@Torin-Shepard-athena  - we are still unable to find a patient with a good list of medications.  Can you assist?

**Comment by Torin-Shepard-athena** [comment]
CPS Clinical resources do not allow searching across patients to avoid HIPAA concerns/risks.  We recognize this creates a challenge/difficulty for API Sandbox users who have no easy way to find sample patients with specific types of clinical data.

Here is a list of sample patients with MedicationStatement resources.

1225794125001060 Marilyn Stone
1239638219050620 Robert Inishi
1225794119101060 Beth Johnson
1225794125101060 Carl Nyberg
1225794126101060 Bill Vario
1225794127051060 Tina Giralomondo
1225794129001060 Cindy Stafford

**Comment by jdmaple** [comment]
Awesome!  This was very helpful @Torin-Shepard-athena.
