### ISSUE TITLE
Searching for patients by name

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#118]
How can we do a free text search in FHIR? The API doesn't seem to follow the spec and accept a request like this: 
[base]/Patient?given:contains=eve 

 Reference: From <https://www.hl7.org/fhir/search.html#string>

**Comment by Torin-Shepard-athena** [comment]
The API Server does not support :contains modifier at this time.

Using the :missing modifier with value false with the Patient resource can be used to get a list of all the patients in CPS API Sandbox.

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?family:missing=false&_count=300

The response Bundle can be parsed to extract patients that match any desired criteria when a FHIR API Server does not support all the search capabilities defined in the FHIR specification.

**Comment by jdmaple** [comment]
This worked perfectly - Thank you!
