### ISSUE TITLE
Sample Patients with Medication Records

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#119]
Can you please provide a list of patients that have Medications and will return data from the MedicationStatement endpoint:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/MedicationStatement?patient=1442678381200620

**Comment by Torin-Shepard-athena** [comment]
This looks like a duplicate of [Issue #117](https://github.com/virencehealth/apiserver.virencehealth.com/issues/117)

**Comment by jdmaple** [comment]
Closing - duplicate for issue #117
