### ISSUE TITLE
DocMap help

### ISSUE THREAD

**Issue by JayJMobley** [virencehealth/apiserver.virencehealth.com#120]
Looking for some guidance here using the CDA DocMap in CPS to pull in an unbound value in a TOC for 'Reason for Visit' 

The online documentation seems to indicate that we can somehow use 
MakeTextConcept(%REFERRALREASON%) to pull in the 'reason for referral' 

I just need some help connecting the dots here. Where can I add this in the DocMap feature for CDA 2.1. to cause that reason to pull into the CDA from the Order in CPS?

**Comment by Rinkal-jain** [comment]
Mapping from online documentation is for internal use and used by FHIR server. 
Its nothing to do with DOCMAP definition.

 

Are you trying to add 'Reason for Visit' section in TOC document?

 

If yes, you need to do some modifications to docmap definition 'TOCReferralBody.docmap' to add this section.
For this your can either use CCDA Designer or directly do changes in TOCReferralBody.docmap (path is mentioned in below notes).
In case you are doing changes directly to TOCReferralBody.docmap file, add below configuration to "map" array in the same file. 
        {
            "name": "Reason for Visit Section",
            "xformURL": "$XFORMBASE/xlate/fhir",                    
            "queryString": "$FHIRBase/Observation?subject=$patientId&code=29299-5,900033&encounter=$encounterId&_count=1000&status:not=entered-in-error",            
            "ruleURL": "$PERSISTENTSTORAGE/ReasonForVisit.xsl"
        }
You can refer CVSBody.docmap for the same.

 


NOTE: DOCMAP definition are the configuration files which defines how CDA of particualr type can be generated
from CPS. You can find these files under "...\Centricity Practice Solution\jboss\standalone\deployments\cda-generator-master.war\WEB-INF\docmap".
Please take back up of these files before you do any changes.

**Comment by rashmi1977** [comment]
As we have not received any further communication related to this issue, we are closing the same
