### ISSUE TITLE
How to create patient record along with guarantor using rest?

### ISSUE THREAD

**Issue by balajee500** [virencehealth/apiserver.virencehealth.com#121]
I want to create patient record along with guarantor information using patient rest end point. Could you please share the sample JSON body?

**Comment by ychowdhary** [comment]
Sample JSON Payload:
{
    "resourceType": "Patient",
    "extension": [
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
            "valueBoolean": false
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
            "valueReference": {
                "reference": "RelatedPerson/G-11_1899544078211140"
            }
        }
    ],
    "active": true,
    "name": [
        {
            "use": "official",
            "family": [
                "Patient1"
            ],
            "given": [
                "Test",
                "Sample"
            ],
            "prefix": [
                "Mrs."
            ]
        },
        {
            "use": "nickname",
            "given": [
                "Patient1"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "978456",
            "use": "work"
        },
        {
            "system": "phone",
            "value": "978123",
            "use": "home"
        },
        {
            "system": "phone",
            "value": "978789",
            "use": "mobile"
        },
        {
            "system": "email",
            "value": "cercei.lanni@xyz.com"
        }
    ],
    "gender": "female",
    "birthDate": "1992-01-31",
    "deceasedBoolean": false,
    "address": [
        {
            "line": [
                "4 joseph Street"
            ],
            "city": "Acton",
            "state": "MA",
            "postalCode": "01720",
            "country": "USA"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/v3/MaritalStatus",
                "code": "M",
                "display": "Married"
            }
        ],
        "text": "Married"
    },
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "sv",
                        "display": "Swedish"
                    }
                ],
                "text": "Swedish"
            },
            "preferred": true
        }
    ],
    "careProvider": [
        {
            "reference": "Practitioner/1225652498001060"
        }
    ],
    "managingOrganization": {
        "reference": "Organization/LO-1225648232001060"
    }
}

If the **ge-patient-extension-patientAsGuarantor** value is set as **true** then the Guarantor is the same as the patient.

**Comment by balajee500** [comment]
@ychowdhary Thanks!
