### ISSUE TITLE
Simplest authentication method for creating patient through REST.

### ISSUE THREAD

**Issue by balajee500** [virencehealth/apiserver.virencehealth.com#123]
@KedarGanta @JonTGE @Puttajunjaiah @praneetlokege @Rinkal-jain  Right now, I am using Oauth flow as authentication for creating patient which is more complex. Is there any simple authentication method available for creating patient (ex: username-password authentication flow)?

If yes, Please share the documentation for refence or provide the steps here. Thanks.

**Comment by Rinkal-jain** [comment]
You can use the native flow to generate access token:
1)request url to generate access token:
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token?grant_type=client_credentials&scope=user/*.*

2)with sample provider login credentials(username and password details also present at developer portal:https://mydata.athenahealth.com/access-centricity-apis)
User Name: hwinston@sboxprovtenant.com
	Password: TestProvider!@
        
![native-flow](https://user-images.githubusercontent.com/46125477/77319046-241f9d00-6d34-11ea-9f4d-ba67d5a50f7e.png)

**Comment by balajee500** [comment]
Thanks @Rinkal-jain
