### ISSUE TITLE
How to add Custodial, Demographics, Income and Housing Survey details to a patient record?

### ISSUE THREAD

**Issue by balajee500** [virencehealth/apiserver.virencehealth.com#124]
@Rinkal-jain @praneetlokege @KedarGanta @JonTGE I am getting custodial, demographics, income and housing survey details of patient. I want to add these information to the patient record through REST end point. Could you share the document and example code for referece?  Thanks.

**Comment by nkadmane** [comment]
Custodial and demographics information can be added by performing below API calls on FHIR server. 

- Custodial: FHIR RelatedPerson resource captures the patient's custodial information. Create operation on RelatedPerson can be used to add custodial information for a particular patient.

- Demographics: While performing Create operation on Patient, patient's demographic information can be added in request body.

Please refer below link to get more details on API resources supported by FHIR server: 
**https://mydata.athenahealth.com/**

Regarding income and housing survey details, sorry to say but it is not currently supported by FHIR server.
