### ISSUE TITLE
How to create a sandbox or production instance?

### ISSUE THREAD

**Issue by balajee500** [virencehealth/apiserver.virencehealth.com#125]
@Puttajunjaiah @KedarGanta @JonTGE @praneetlokege @Rinkal-jain I am new to centricity API. I do not know to create a prodution or sandbox instance for storing healthcare information. could you please provide a steps to create production or sandbox environment? Thanks!

**Comment by Puttajunjaiah** [comment]
Could you please elaborate your query a little further? Just to clarify, the sandbox is hosted by Athena and the documentation on how to access APIs is available at https://mydata.athenahealth.com/.
