### ISSUE TITLE
Scope for sandbox work account changed

### ISSUE THREAD

**Issue by royyin224** [virencehealth/apiserver.virencehealth.com#127]
**Describe the bug**
The access scope for sandbox work account (hwinston@sboxprovtenant.com) has changed and we can no longer get following data for test purpose:

1. Practitioners
2. Locations
3. Appointments
4. Patients

currently, the allowed scope for this account are:

1. user/ValueSet.read 
2. user/Medication.read 
3. openid 
4. profile 
5. user/Binary.read 
6. user/ConceptMap.read 
7. user/NamingSystem.read 
8. offline_access user/OperationDefinition.read

**To Reproduce**
1. Get access token from https://cpsapisandbox.virenceaz.com:9443 requesting for scope "openid", "profile", "offline_access" and "user/\*.\*"
2. Use the access token returned by step 1 to retrieve data from URL https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_count=500&_format=json

**Expected behavior**
Test work account should return test data when requesting following resources:

1. Practitioners
2. Locations
3. Appointments
4. Patients

**Screenshots**
Response coming back from the API
![image](https://user-images.githubusercontent.com/9049754/77040680-59a24e80-69f3-11ea-8cc5-66207950f85c.png)

**Comment by Torin-Shepard-athena** [comment]
Something may have happened to this work account temporarily. This sandbox is periodically reset, and the account seems to be working properly on the afternoon of March 20, 2020.

**Comment by royyin224** [comment]
@Torin-Shepard-athena Thanks, I can read those resources again
