### ISSUE TITLE
Patient Id in the response of patient create REST API

### ISSUE THREAD

**Issue by balajee500** [virencehealth/apiserver.virencehealth.com#128]
I am creating patient record using centricity rest api. However, i need created **patient id in the response**. so, Please help me with this. Thanks.

**Comment by Rinkal-jain** [comment]
1)If you are using FHIR and creating patient using the following URL:
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient

![issue-128](https://user-images.githubusercontent.com/46125477/77415450-85a14380-6de8-11ea-8697-74aea123379a.png)


2)then in the headers(Content-location or Location) of the response you will get patientID and the URL to get the created patient:

![issue-128a](https://user-images.githubusercontent.com/46125477/77416950-a2d71180-6dea-11ea-91bb-db74902aac68.png)

![issue-128b](https://user-images.githubusercontent.com/46125477/77417405-5213e880-6deb-11ea-9772-80c778ddae00.png)

**Comment by balajee500** [comment]
Thanks @Rinkal-jain
