### ISSUE TITLE
MedicationAdministration - Empty Result-sets 

### ISSUE THREAD

**Issue by developer1254** [virencehealth/apiserver.virencehealth.com#130]
Hi @Torin-Shepard-athena , 

Thank you for your responses on other threads. They have been really helpful on getting us connected. 

I created a tester application to locate patients with applicable data for our portal. I was able to locate result-sets for each call expect 'MedicationAdministration'. Would it be possible to get some data added to at least one patient so we can pull down a response?

**Comment by developer1254** [comment]
Any update?

**Comment by nkadmane** [comment]
Early this week we have scheduled a meeting to get couple of MedicationAdministration data added for one of the patient.
Once done, we will let you know.

**Comment by nkadmane** [comment]
For patient Walter Caldwell, three MedicationAdministration data has been added. 
Please verify if you are getting the response back in the GET API call.

**Comment by developer1254** [comment]
Thank you. I was able to pull down the response.
