### ISSUE TITLE
Sandbox Patient Data Manipulations

### ISSUE THREAD

**Issue by developer1254** [virencehealth/apiserver.virencehealth.com#131]
Hi @Torin-Shepard-athena,

We are trying to wrap up some workflows and do end-to-end testing. Would be be possible to get some data manipulated in the sandbox to match variables we are expected on our side? 

Below is a table of the data we would like to get added/modified against 4 individual test patients in the sandbox. How do we go about getting these changes pushed against some patient records?

Patient | Insurance    Coverage | Medications
-- | -- | --
1 | Member ID:   Z0296432700 | Provigil 200 MG Oral Tab. Qty: 30 Days’ Supply 30.  Dispense as Written.  RxCUI: 213471       Risperdal 4 MG Oral Tab. Qty: 30 Days’ Supply 30.  Dispense as Written.  RxCUI:    104784       Fortamet 24 ER 1000 MG Extended Release Oral Tab. Qty: 30 Days’   Supply 60.  No DAW. RxCUI:   1807894       Olmesartan/HCT 40-25mg Tab.    Qty: 30 Days’ Supply 60.  No   DAW.  RxCUI: 403855
2 | Member ID:    S0002120200 | Topamax 200 MG Oral Tablet.    Qty: 60 Days’ Supply 30.    Dispense as Written: RxCUI:  199890       Risperdal 2 MG Oral Qty: 30 Days’ Supply 30.  Dispense as Written. RxCUI:  104782       Aricept 23 MG Oral Tablet.    Qty: 30 Days’ Supply 30.  No DAW.   RxCUI:   1100184       Invega 6 MG Extended Release Oral Tablet.  Qty: 30 Days’ Supply 30.  Dispense as Written. RxCUI:  686443       Trimipramine 25mg Cap. Qty: 30 Days’ Supply 30.  No DAW. RxCUI:   313498
3 | Member ID:   Z9595959501 | Keppra 100 MG/ML Oral. Qty: 150 Days’ Supply 30.  Dispense as Written. RxCUI:   404595       Abilify 30 MG Oral Tablet. 30 Days’ Supply 30.  Dispense as Written. RxCUI:      352310   Risperdal 3 MG Oral Tablet. 30 Days’ Supply 30.  Dispense as Written. RxCUI:   104783       Invega 6 MG Extended Release Oral Tablet. 30 Days’ Supply   30.  Dispense as Written. RxCUI:   686443       Topiramate 200mg ER Cap. 30 Days’ Supply 30.  No DAW. RxCUI:  199890
4 | Payor Name:   ‘Not BSC’       Any Member ID: doesn’t mater | Plavix 75 mg tablet.  No   DAW. RxCUI:  309362       Crestor 10 mg oral tablet. Dispense as Written. RxCUI:  859749       Ambien 5 mg.  No DAW.   RxCUI:  854876

**Comment by nkadmane** [comment]
We have added the requested data for the four different patients. PFB the name of patients and the documentId/encounterId in which the medications data has been added.

Patient #1 : 
Name : Jeff Abbey
DocumentID : 1903092511245710

Patient #2 : 
Name : Brad Boyd
DocumentID : 1903092775246110

Patient #3 : 
Name : Matt Downe
DocumentID : 1903093056246510

Patient #4 : 
Name : Darrell Hagen
DocumentID : 1903093346246910
