### ISSUE TITLE
Developer center cannot be accessed

### ISSUE THREAD

**Issue by royyin224** [virencehealth/apiserver.virencehealth.com#132]
**Describe the bug**
The developer center to manage API end points are no more accessible.

**To Reproduce**
Access the URL https://mydata.gehealthcare.com/access-centricity-apis#sec2, using Chrome.

**Expected behavior**
It should open up the developer central web page for API end point management, it still opens a few days ago using the same terminal in the same network.

**Screenshots**
![image](https://user-images.githubusercontent.com/9049754/81536986-12a35a80-939f-11ea-9037-504f09299b22.png)

**Comment by KedarGanta** [comment]
@royyin224  Please use this URL https://mydata.athenahealth.com/home

Note: Both CPS and CEMR products are acquired from GE Healthcare business and now operate under athenahealth as athenaPractice and athenaFlow respectively

**Comment by royyin224** [comment]
Thanks, I can access the developer center
