### ISSUE TITLE
Not Authorized Issue

### ISSUE THREAD

**Issue by greg-peters** [virencehealth/apiserver.virencehealth.com#136]
When calling Sandbox environment's FHIR schedule API, the follow response is returned.

URL Called: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule
 Bearer is passed in the header with authorization code.

<OperationOutcome xmlns="http://hl7.org/fhir"><text>
		<status value="generated" />
		<div xmlns="http://www.w3.org/1999/xhtml">
			<table width="100%">
				<tbody>
					<tr>
						<td width="25%"><span class="text-muted">Outcome null</span></td>
						<td width="42%">
							<span class="text-muted"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>PROCESSING</td><td>Not authorized</td></tr></tbody></table></span>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</text>
	<issue>
		<severity value="error" /><code value="processing"/><diagnostics value="Not authorized"/></issue></OperationOutcome>

**Comment by Amits2070** [comment]
Hi,
I think you are trying to access FHIR API using Authorization code.
Please use this authorization code to get the access token first and using this access token you can access the FHIR API's.
Please follow the detail steps mention in the link https://mydata.athenahealth.com/access-centricity-apis for FHIR api access.

**Comment by greg-peters** [comment]
> Hi,
> I think you are trying to access FHIR API using Authorization code.
> Please use this authorization code to get the access token first and using this access token you can access the FHIR API's.
> Please follow the detail steps mention in the link https://mydata.athenahealth.com/access-centricity-apis for FHIR api access.

Can you provide a Schedule id to test with on the Sandbox Environment?

**Comment by Amits2070** [comment]
Please try some of following end point for Schedule to test with on the Sandbox Environment

Schedule id :- 
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?_id=31
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?_id=32
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?_id=33

Actor :- 
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?actor=Practitioner/1588761792000070

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?actor=Practitioner/1588761792000080

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?actor=Practitioner/1588761792000100

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?actor=Practitioner/1588761792000020
