### ISSUE TITLE
Getting change password message for hwinston@sboxprovtenant.com!

### ISSUE THREAD

**Issue by sr5732358** [virencehealth/apiserver.virencehealth.com#137]
**Your question**

Hi there.  I've been working with the sandbox and the work account hwinston@sboxprovtenant.com.  Today when I signed in with the hwinston@sboxprovtenant.com test account I was prompted to chance password.  It seemed like I should not be getting this.  I did not proceed.  I've included a link to the screenshot I received here  [https://www.dropbox.com/s/k94zt8008ndwj85/Screen%20Shot%202020-06-12%20at%201.45.22%20PM.png?dl=0](url)

For now:
Can I continue to use this user?
What is the password to use?

For the future:
Can I ignore password change messages?  Could I simply change the password to move past this screen... but then continue to use the old password for all requests and have it work?

**Comment by Torin-Shepard-athena** [comment]
We apologize for the delay.  The password has been restored so you can continue to use the sample hwinston account.
