### ISSUE TITLE
Lease has expired on ID | Solutionreach

### ISSUE THREAD

**Issue by dianalynshull** [virencehealth/apiserver.virencehealth.com#139]
I'm getting the following error when one of our client's attempts to run on the HCO integration:

<JavaException><JavaException>  <Type>com/idx/hco/HCOMessageError</Type>  <Message><![CDATA[Lease has expired on ID]]></Message> 

Is this indicating that there is something wrong with this office's ID? Do we need to verify that we have the correct Connection Name and User Name?

Thanks!

**Comment by Torin-Shepard-athena** [comment]
Please provide more detail, explanation, and clarification about what is meant by HCO integration.  Was this question/issue posted on the proper forum?

**Comment by dianalynshull** [comment]
Hi Torin,

I was directed here by our integration partner, I'm with solutionreach. We have an integration with Centricity HCO but are getting the following errors:

<JavaException><JavaException>  <Type>com/idx/hco/HCOMessageError</Type>  <Message><![CDATA[Lease has expired on ID]]></Message>  <StackTrace><![CDATA[com.idx.hco.HCOMessageError: Lease has expired on ID at com.idx.hco.HCObject.message(HCObject.java:604) at com.idx.hco.dbms.DBMSQuery.retrieve(DBMSQuery.java:108) at com.idx.hco.dbms.TableQuery.retrieve(TableQuery.java:124)   at Codemesh.JuggerNET.JavaClass.ThrowException(Exception ex)   at Codemesh.JuggerNET.NTypeValue.Throw(Int64 inst)   at Codemesh.JuggerNET.JavaClass.ThrowTypedException(Int64 inst)   at Codemesh.JuggerNET.JavaMethod.CallObject(JavaProxy jpo)   at com.idx.hco.dbms.TableQuery.retrieve()   at CentricityBusinessHCO.AppointmentService.DoRequest(Connection connection)   at CentricityBusinessHCO.Service`1.ProcessData()   at CentricityBusinessHCO.Main.ProcessServicesAndReaders(Subscriber[] subscribers)   at CentricityBusinessHCO.Main.ExtractAll(Subscriber[] subscribers)]]></StackTrace></JavaException>
com.idx.hco.HCOMessageError: Lease has expired on ID at com.idx.hco.HCObject.message(HCObject.java:604) at com.idx.hco.dbms.DBMSQuery.retrieve(DBMSQuery.java:108) at com.idx.hco.dbms.TableQuery.retrieve(TableQuery.java:124)   at Codemesh.JuggerNET.JavaClass.ThrowException(Exception ex)   at Codemesh.JuggerNET.NTypeValue.Throw(Int64 inst)   at Codemesh.JuggerNET.JavaClass.ThrowTypedException(Int64 inst)   at Codemesh.JuggerNET.JavaMethod.CallObject(JavaProxy jpo)   at com.idx.hco.dbms.TableQuery.retrieve()   at CentricityBusinessHCO.AppointmentService.DoRequest(Connection connection)   at CentricityBusinessHCO.Service`1.ProcessData()   at CentricityBusinessHCO.Main.ProcessServicesAndReaders(Subscriber[] subscribers)   at CentricityBusinessHCO.Main.ExtractAll(Subscriber[] subscribers)

Should I be posting this elsewhere?

Thanks!

**Comment by Torin-Shepard-athena** [comment]
This forum is for working with athenaPractice/athenaFlow (formerly CPS/CEMR) FHIR APIs.  HCO integration is now part of athenaIDX.

If you are still experiencing the issue, can you please provide an email address or other information to make it possible to contact Solutionreach outside of this forum?
