### ISSUE TITLE
Appointment Types

### ISSUE THREAD

**Issue by soneal-relatient** [virencehealth/apiserver.virencehealth.com#140]
Is there a way through the API to pull a list of appointment types usable to schedule or search available slots?

Our team has looked into the following ValueSets:

- APPOINTMENTTYPE
- C80APPOINTMENTTYPECPS
- C80APPOINTMENTTYPEEMR

But it does not appear to us that these values are the appropriate values to use with the /Slot and /Appointment endpoints.

Can we get some clarification about what appointment types are utilized and how we can pull these values from the API?

**Comment by soneal-relatient** [comment]
Is it possible to get an update on this?

**Comment by Amits2070** [comment]
You can not schedule or search available slots based on Appointment Types. Please go through https://mydata.athenahealth.com/fhirapidoc. for more details.

This end points will give you code and Display Value for appointment type in CPS and EMR.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/ValueSet/C80APPOINTMENTTYPECPS
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/ValueSet/C80APPOINTMENTTYPEEMR

You can find list of appointment type in the CPS under the report section, Attaching screen shot for same.

Note:  "There are no API available to pull list of appointment type"
![image](https://user-images.githubusercontent.com/64770988/86353446-d85e8700-bc84-11ea-9b8f-f8a1d7ce4e0e.png)

**Comment by soneal-relatient** [comment]
@Amits2070 Thank you for the response. Our team is slightly confused on integrating a scheduling application with the API. Given that there is not an available API to pull list of appointment types does this mean we would need to interact with the practice to get the types and all information we need to make scheduling requests?

Also if appointment types are not able to be pulled from the API but the C80*CPS|EMR value sets are then what are the differences between those value sets and the APPOINTMENTTYPE value set?

**Comment by Amits2070** [comment]
We may support searching list of AppointmentType and search appointments based on AppointmentType in future releases.

ValueSet for APPOINTMENTTYPE represents appointment participant type code for practitioner as participant (will be act as primary performer) and This is mandatory field we give in appointment payload.
Example:- 
<Appointment xmlns="http://hl7.org/fhir">
   <participant>
        <type>
            <coding>
                <system value="http://hl7.org/fhir/v3/ParticipationType"/>
                <code value="PPRF"/>
                <display value="primary performer"/>
            </coding>
            <text value="primary performer"/>
        </type>
        <actor>
            <reference value="Practitioner/1588761792000020"/>
        </actor>
    </participant>   
</Appointment>

ValueSet for C80APPOINTMENTTYPECPS /C80APPOINTMENTTYPEEMR represents appointment type codes and text value.
Example:- 
    <participant>
		<type>
			<coding>
				<system value="http://hl7.org/fhir/v3/ParticipationType"/>
				<code value="PPRF"/>
				<display value="primary performer"/>
			</coding>
			<text value="primary performer"/>
		</type>
		<type>
			<coding>
				<system value="http://hl7.org/fhir/ValueSet/c80-practice-codes"/>
				<code value="408480009"/>
				<display value="Allergy/Immunology"/>
			</coding>
			<text value="Allergy/Immunology"/>
		</type>
		<actor>
			<reference value="Practitioner/1588761792000090"/>
		</actor>
  </participant>

Please go through **https://www.hl7.org/fhir/DSTU2/valueset-c80-practice-codes.html** and **https://www.hl7.org/fhir/DSTU2/appointment.html#def**  for more clarification.

**Comment by soneal-relatient** [comment]
Ok thank you. So it is not possible to search for available slots using the C80 appointment types?

We are working on a system that will allow patients to search for available slots and our standard flow is to give the following options:

- Location
- Practitioner
- Date Range
- Appointment Type

Judging from this information this might not be possible? Am I understanding that correctly?

**Comment by Amits2070** [comment]
We support searching Slot based on following parameters
1. _id 
2.  fb-type  (The free/busy status of the appointment)
     **Possible Values** 
     1   Busy
      0   Available
    -1   busy-unavailable
    ****
3. identifier 
4. schedule
5. slot-type
6. start (date )
7. start-fromnow

Example :
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Slot?_id=622450
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Slot?slot-type=49
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Slot?fb-type=-1

**Comment by soneal-relatient** [comment]
A couple things:

- Searching with numeric value for fb-type does not work. It only accepts string values from what I tested.
- I attempted to use the code values for the C80 appointment types for **slot-type** but those did not work. The example you gave did work, however. What is that _49_ corresponding to as it is not part of the C80 appointment type value sets.

**Comment by Amits2070** [comment]
1. Currently in CPS 12.3 (i.e sandbox 12.3) don't have any API to query the list of appointment types is a known limitation in CPS 12.3. An enhancement will be available in athenaPractice v20 release to provide an API to lookup appointment types.
E.g :- https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment/$lookup-type?practitioner=1225652472001060 
This will give list of appointment type(containing appttypeID and appttypeName).But this will not work in 12.3(i.e current sandbox version)

2.   C80 appointment type are specialty codes for the Practitioner participant of the appointment and will not work in Slot\slot_type search parameter.
To continue with your development you can use any one from list of appttypeID (you can find it in attached file) and can apply in Slot\slot_type search parameter.
