### ISSUE TITLE
Query for Centricity API Integration - Payment Posting and related APIs

### ISSUE THREAD

**Issue by rahul-chetu** [virencehealth/apiserver.virencehealth.com#141]
We are process we are able to generate the access token for the APIs using Application Service Authentication.

Now we can access the other APIs but having some trouble with parameters.

Query :
Is there any reference/sample for Request with all parameters for the payment $Posting API and other depending APIs for payment $posting. 

Some Errors sample we facing:
"issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Appointment] with parameters [[_summary, actor , _format, status]]"
        }
    ]
"issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[$Posting] with parameters [[_summary]]"
        }
    ]

**Comment by Amits2070** [comment]
For post payment below API can be used and here is the sample payload:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$PostPayment : POST

Request Body:
<Basic xmlns="http://hl7.org/fhir">

                <extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-batch">

                                <valueInteger value="1169"/>

                </extension>

                <extension url="BatchName">

                                <valueString value="dv-10202009" />

                </extension>

                <extension url="TicketNo">

                                <valueString value="OV003582" />

                </extension>

                <extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-patientVisitId">

                                <valueInteger value="4900"/>

                </extension>

                <extension url="Source">

                                <valueString value="Patient" />

                </extension>

                <extension url="PaymentType">

                                <valueString value="Cash" />

                </extension>

                <extension url="PayerType">

                                <valueString value="Patient" />

                </extension>

                <extension url="Amount">

                                <valueString value="500.00"/>

                </extension>

                <extension url="PayerId">

                                <valueDecimal value="1009843200000000"/>

                </extension>

                <extension url="TransactionDistribution">

                                <valueString value="Yes" />

                </extension>

</Basic>

 Please replace the correct values for BatchNumber, BatchName, TicketNo, PatientVisitId, Amount and PayerId

**Comment by rahul-chetu** [comment]
Here is the Curl request sample i am using : 

curl -X POST \
'https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment?patient=1442678382750620' \
-H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSIsImtpZCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSJ9.eyJhdWQiOiI1ZmFiNDZiZC03YmEyLTQxMzktYWUzZS01ZmUyNzlhODRkNzAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9iMzFkZmUwNi02MmJmLTQ3OWUtYjA2YS1mMTlmOWNjMGZkZjUvIiwiaWF0IjoxNTkzNzE5MTQ3LCJuYmYiOjE1OTM3MTkxNDcsImV4cCI6MTU5MzcyMzA0NywiYWNyIjoiMSIsImFpbyI6IkUyQmdZSGgrbXNtcjhHaWp5djRGSnUrMm1mL2dyM3RUNG5mMytaeHByWW5HNW5IV00xb0EiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiNWZhYjQ2YmQtN2JhMi00MTM5LWFlM2UtNWZlMjc5YTg0ZDcwIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJXaW5zdG9uIiwiZ2l2ZW5fbmFtZSI6IkhhcnJ5IiwiaXBhZGRyIjoiMTA0LjQyLjYzLjc1IiwibmFtZSI6IkhhcnJ5IFdpbnN0b24iLCJvaWQiOiI4ZGJmMTY5OC01NjA4LTQxZjUtOTNmMC1lNjY4ODIzMmUyZjQiLCJyaCI6IjAuQVM0QUJ2NGRzNzlpbmtld2F2R2ZuTUQ5OWIxR3ExLWllemxCcmo1ZjRubW9UWEF1QUlBLiIsInNjcCI6IkRpcmVjdG9yeS5BY2Nlc3NBc1VzZXIuQWxsIEdyb3VwLlJlYWRXcml0ZS5BbGwgb3BlbmlkIFVzZXIuUmVhZCBVc2VyLlJlYWQuQWxsIFVzZXIuUmVhZEJhc2ljLkFsbCBVc2VyLlJlYWRXcml0ZSBVc2VyLlJlYWRXcml0ZS5BbGwiLCJzdWIiOiJRSEV1b2FlMGF2Uk1lbW1obGhDa1h6MXhKbml6TVkyQ0FhNGlmZ29yNTU4IiwidGlkIjoiYjMxZGZlMDYtNjJiZi00NzllLWIwNmEtZjE5ZjljYzBmZGY1IiwidW5pcXVlX25hbWUiOiJod2luc3RvbkBzYm94cHJvdnRlbmFudC5jb20iLCJ1cG4iOiJod2luc3RvbkBzYm94cHJvdnRlbmFudC5jb20iLCJ1dGkiOiI0bVFpS2JFcUFVNk1YajBrRlo1X0FBIiwidmVyIjoiMS4wIn0.NWKBZ2hCiupohefFMzdpnsFCJLv1Vjts5ds574gDHFi2u6FZtBLGTVIrWrI7GezLzdrOA722ZZNl3ce3PSTkqMmRhILeLmBbXW3pe-zRaTkAsdCZMugwzRx19RKXZo5lvYiHFy40Q6Wg2-dhAe__fEkcmpCoNFqdKxIP7WUv1HjWxntn1VVl3q4lZLgpW99cD5m8-lD0Zd3DXzT3MBm4PwYWm9x6raIFrpiGpmQK_DoEAKwlyBVQVMkOLd49v5p-I1_5MBlvsOtu8UuXfG3Xh0uzWW-6QBMmz_busESm7JDWyIksKiHCkIbbwyzkesBcLdWjF4vnISYPU_9cRjffKA~~e0ea09bf1a6ff41909403214ca683a02e5cdaa555ef53c5c143d70ce1f33eca09495cc1ab2d24af3a1a822964bf398bcd7f20e4ac1760e32b9c731830ff46c27' \
-H 'cache-control: no-cache' \
-H 'content-type: text/xml' \
-H 'postman-token: 85c4aeab-e057-525b-ace8-e61aeea2bcd5' \
-d '
<extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-batch">
   <valueInteger value="1169"/>
</extension>
<extension url="BatchName">
   <valueString value="dv-10202009" />
</extension>
<extension url="TicketNo">
   <valueString value="OV003582" />
</extension>
<extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-patientVisitId">
   <valueInteger value="4900"/>
</extension>
<extension url="Source">
   <valueString value="Patient" />
</extension>
<extension url="PaymentType">
   <valueString value="Cash" />
</extension>
<extension url="PayerType">
   <valueString value="Patient" />
</extension>
<extension url="Amount">
   <valueString value="500.00"/>
</extension>
<extension url="PayerId">
   <valueDecimal value="1009843200000000"/>
</extension>
<extension url="TransactionDistribution">
   <valueString value="Yes" />
</extension>
'

Attached the Error :
![image](https://user-images.githubusercontent.com/61985382/86406691-387b1a80-bcd1-11ea-8ac4-47e387cdbb42.png)


**Please let me know the APIs to get the BatchNumber, BatchName, TicketNo. Also how can we create new batch for payment.**

**Comment by Amits2070** [comment]
There is no direct API to get the BatchNumber, BatchName, TicketNo. For more details please go through https://mydata.athenahealth.com/fhirapidoc . Values for Extenstion URL "http://hl7.org/fhir/StructureDefinition/ge-posting-batch" and  Extenstion URL "BatchName" will create the new batch for payment. Please find sample payload for successful posting of payment payload in sandbox.

Request Url : https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$PostPayment  (POST)

Request Body : 
<Basic xmlns="http://hl7.org/fhir">

                <extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-batch">

                                <valueInteger value="93"/>

                </extension>

                <extension url="BatchName">

                                <valueString value="BarbaraO_20020711" />

                </extension>

                <extension url="TicketNo">

                                <valueString value="000001" />

                </extension>

                <extension url="http://hl7.org/fhir/StructureDefinition/ge-posting-patientVisitId">

                                <valueInteger value="1"/>

                </extension>

                <extension url="Source">

                                <valueString value="Patient" />

                </extension>

                <extension url="PaymentType">

                                <valueString value="Cash" />

                </extension>

                <extension url="PayerType">

                                <valueString value="Patient" />

                </extension>

                <extension url="Amount">

                                <valueString value="500.00"/>

                </extension>

                <extension url="PayerId">

                                <valueDecimal value="1009843200000000"/>

                </extension>

                <extension url="TransactionDistribution">

                                <valueString value="Yes" />

                </extension>

</Basic>

**Comment by rahul-chetu** [comment]
"Also there is no direct API to get the BatchNumber, BatchName, TicketNo."

Then how I can get the TicketNo as Ticket number and patient visit id combination must be a match for $PostPayment.

Let me know the indirect way to fetch the above data for test patients.

I Looked into
- PRACTICE MANAGEMENT APIS
- CLINICAL APIS
- SYSTEM APIS

TicketNo keyword was only used in Delete Operation for PostPayment.

Please provide the flow to get all the required data for PostPayment(direct/indirect).

**Comment by Amits2070** [comment]
It is a known limitation the API Server does not output batch name.  This may be considered for a future release.

Specify a new batch name without any batch number in the $PostPayment request body so the API Server will create a new batch.

The Account page of the API documentation is missing the important fact that the $Account FHIR resource id value is a ticket number.

The id and ge-account-patientVisitId extension elements in $Account resources give the TicketNo and ge-posting-patientVisitId values to put in body of $PostPayment POST requests.

Example: $Account?subject=1442678385550620 returns Bundle of 3 Account resources for this test patient.
TicketNo 000391 and VisitId 388
TicketNo 000390 and VisitId 387
TicketNo 000383 and VisitId 380

Any of these 4 pairs could be used in $PostPayment POST request body.

**Comment by rahul-chetu** [comment]
Thanks for your responses. Now I am able to do post payment. 

Success Response :
<Parameters xmlns="http://hl7.org/fhir">
   <parameter>
      <name value="message"/>
      <valueString value="The operation is successful."/>
   </parameter>
</Parameters>

**Still have some queries:** 

- How I can get the available different payment Sources like Patient, insurance, etc. 
- How can I get Payer Id for different types including Patient as currently, I used payerId mentioned in paymentpayload.docx.
          <subject>
                    <reference value="Patient/1442678381950620"/>
          </subject>
          I assumed 1442678381950620 as PayerId but that dont worked.

How can I get posted id to retrieve the details again using https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Posting?_id=516

**Comment by Amits2070** [comment]
If you are able to post payment successfully can you please open new issue for other related questions and close this.

You can get other payment Sources like Patient, insurance with help of following API's

For Insurance :
 https://<server>/CentricityPracticeFHIRServer/fhir/Coverage?searchcriteria=searchvalue 
Ex: "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Coverage?subscriber=1442678382750620" (subscriber = patient id)
search parameters
 _id
_lastUpdated 
group
identifier 
type 
issuer
subscriber

For Patient
The Account resource is returning payment details which are initiated by Patient.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Account?_id=000083
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Account?_id=000085

To get the posting id after $PostPayment .
After successful posting of payment under header tab you will get the required ID to use in https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Posting?_id=516

![image](https://user-images.githubusercontent.com/64770988/87286754-e16a1680-c516-11ea-9568-6a7e9d425de9.png)

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu Here is a response to a question you asked in July 2020 comment.

After successful $PostPayment, how can we get the new {postingId} to be able to retrieve the details as a Posting resource
[base]/$Posting?_id={postingId}

Here is one suggestion assuming you have the {patientid} that was embedded in the body of the POST $PostPayment request.
Search $Posting by subject and _lastUpdated greater than the timestamp just before you performed the $PostPayment.
[base]/$Posting?subject={patientid}&_lastUpdated=gtYYYY-MM-DDTHH:MI:SS
This should return a Bundle that includes the recently posted payment.

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu
The response to successful $PostPayment contains HTTP header Content-Location with the URL to read the newly posted payment.

This is a more reliable way to get new posting id because $PostPayment operation may use timestamp from visit or other billing objects instead of current time.
