### ISSUE TITLE
Invalid Client Error when attempting to authenticate 

### ISSUE THREAD

**Issue by shayes-phreesia** [virencehealth/apiserver.virencehealth.com#142]
We are actively developing in our AthenaPractice sandbox (v19). We have been using the same API user/ credentials for over a year with no issues. This is an application user not a user through Patient API Access. We have attempted to reset this user's password, but are still getting the same error. As of 6/26, we are getting the following on all attempts to authenticate: 

Request:
GET http://cps.phreesia.me:9080/demo_cpsAPIServer/oauth2/token?client_id=b5d36da4-19bb-4470-bd3e-70745f007770&scope=user/%2A.%2A&aud=a0cb801f-1a90-43c6-9a7b-cbdf6d9ba470&state=test1222&grant_type=client_credentials&redirect_uri=http://EEAZCPSSQL301:9080/demo_cpsAPIServer/oauth2/authorize HTTP/1.1
Authorization: Basic aHdpbnN0b25AZmhpcnByb3ZpZGVyYjJiLm9ubWljcm9zb2Z0LmNvbTpBU0RzIyVkd3I=
User-Agent: PostmanRuntime/7.24.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 1be9ba81-ddbe-4b35-a96b-9fc78df6a37a
Host: cps.phreesia.me:9080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: JSESSIONID=aFZUmQ8qfpWHb3ebvxbQQmbt.EEAZCPSSQL301
 
Response:
HTTP/1.0 401 Unauthorized
Cache-Control: no-store
X-Powered-By: Undertow/1
Set-Cookie: JSESSIONID=ELZTuZloiNC9Dz8gvrmOiFXOB4zZhSqMf5WPyluk.EEAZCPSSQL301; path=/demo_cpsAPIServer
Server: JBoss-EAP/7
Pragma: no-cache
Date: Thu, 25 Jun 2020 16:38:02 GMT
WWW-Authenticate: Basic Realm="274c904f-97c0-4d7f-8f84-80502bfe5f6f"
Content-Type: application/json;charset=utf-8
X-Cache: MISS from web1a.vrn.dataart.net
X-Cache-Lookup: MISS from web1a.vrn.dataart.net:3128
Via: 1.1 web1a.vrn.dataart.net:3128 (squid/2.7.STABLE8)
Connection: close

**Comment by Amits2070** [comment]
This can happen due to multiple reasons
1.Application user may not be present in AAD (Azure Active Directory).
2.Username or Password for this user may not be correct.
3.Application user may not be present in Security group.'API Server User'.

**Comment by shayes-phreesia** [comment]
Hi we are getting this same issue and have verified 2. and 3. - how do we check AAD? @Amits2070 @AjeetYadav07

**Comment by AjeetYadav07** [comment]
To check the application user is present in AAD (Azure Active Directory) follow the below steps :
1. Login to https://portal.azure.com.
2. Select Azure Active Directory in Azure service.
3. Select users in manage.
4. There you will get the list of all users.
