### ISSUE TITLE
Slot Search

### ISSUE THREAD

**Issue by soneal-relatient** [virencehealth/apiserver.virencehealth.com#143]
I am currently discussing in [this thread](https://github.com/virencehealth/apiserver.virencehealth.com/issues/140) how to search slots utilizing appointment types but our team has multiple questions surrounding searching and obtaining slot information that I feel it would be better to open a more generalized question thread.

My team is building out functionality that would allow patients to search for available slots given the following criteria:

- Date Range (start and end date)
- Location(s)
- Practitioner(s)
- Appointment Types

During our development and understanding how the **/Slot** endpoint works it does not seem like we will be able to pass this search criteria over to this endpoint easily. While that is ok if we cannot search this endpoint with all of the options listed above we are wondering about having those values in the return.

It appears to us that information pertaining to the available slot seems to be hidden until search query parameters are passed in. For example, the **slot-type** (which we are assuming is the appointment type for the slot) does not appear in the response unless the **slot-type** query parameter is being utilized.

Without slot-type:
```javascript
{
            "fullUrl": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Slot/622493",
            "resource": {
                "resourceType": "Slot",
                "id": "622493",
                "meta": {
                    "tag": [
                        {
                            "system": "http://hl7.org/fhir/v3/ObservationValue",
                            "code": "SUBSETTED",
                            "display": "Resource encoded in summary mode"
                        }
                    ]
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/ge-slot-facility",
                        "valueString": "3"
                    }
                ],
                "identifier": [
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/v2/0203",
                                    "code": "U",
                                    "display": "Unspecified Identifier"
                                }
                            ],
                            "text": "Unspecified Identifier"
                        },
                        "system": "http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042",
                        "value": "622493"
                    }
                ],
                "schedule": {
                    "reference": "Schedule/29"
                },
                "freeBusyType": "busy",
                "start": "2009-07-12T13:45:00.000Z",
                "end": "2009-07-12T14:00:00.000Z",
                "overbooked": true
            },
            "search": {
                "mode": "match"
            }
        }
```

With slot-type:
```javascript
{
            "fullUrl": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Slot/299398",
            "resource": {
                "resourceType": "Slot",
                "id": "299398",
                "meta": {
                    "tag": [
                        {
                            "system": "http://hl7.org/fhir/v3/ObservationValue",
                            "code": "SUBSETTED",
                            "display": "Resource encoded in summary mode"
                        }
                    ]
                },
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/ge-slot-facility",
                        "valueString": "3"
                    }
                ],
                "identifier": [
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/v2/0203",
                                    "code": "U",
                                    "display": "Unspecified Identifier"
                                }
                            ],
                            "text": "Unspecified Identifier"
                        },
                        "system": "http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042",
                        "value": "299398"
                    }
                ],
                "type": {
                    "coding": [
                        {
                            "code": "49",
                            "display": "60 Min Procedure RmA"
                        }
                    ],
                    "text": "60 Min Procedure RmA"
                },
                "schedule": {
                    "reference": "Schedule/36"
                },
                "freeBusyType": "free",
                "start": "2008-04-14T12:30:00.000Z",
                "end": "2008-04-14T12:45:00.000Z",
                "overbooked": false
            },
            "search": {
                "mode": "match"
            }
        }
```

Given the documentation states that a slot cannot be searched by location nor practitioner directly that seems to us that we will not be able to get information. I do see that the schedule is associated with the slot so we can utilize that endpoint to pull the practitioner, but the location is also not present on that page.

We have been attempting to build out this scheduling functionality for almost a month and can no longer move forward with development given the issues above. It would help us immensely to know if we are able to get this information from the API response or to have a way to search for available slots given the options listed above.

**Comment by soneal-relatient** [comment]
Is it possible to get any information on this?

**Comment by AjeetYadav07** [comment]
The information which is not a available for a particular slot or schedule will not be displayed. If a particular slot is not having slot-type the slot-type coding is not available. 
Schedule resource does not have location element in the supported search parameter.

**Comment by Torin-Shepard-athena** [comment]
@soneal-relatient
@rahul-chetu
The :missing modifier can be in this context.

The following query will return a Bundle of Slot resources that do NOT have any type assigned.
Slot?schedule=36&slot-type:missing=true

The following query will return a Bundle of Slot resources that DO have type assigned.
Slot?schedule=36&slot-type:missing=false
