### ISSUE TITLE
Sample Clinical Data

### ISSUE THREAD

**Issue by soneal-relatient** [virencehealth/apiserver.virencehealth.com#144]
We are currently building out functionality to pull and update patient's clinical data.

We are following the HL7 response structure but we also would like to verify the data structure being returned using test data. Our developers have questions around the following points of data:

* Within allergies, example allergies do not contain reactions
* Not sure how quantity works in medications
* Not sure if problems are supported at all
* Do not have an example of an immunization
* Do not have an example of vitals
* Example I have of social history seems to be missing pieces. Need a more defined example cause it doesn’t seem to match HL7 docs
* Do not have an example of family medical history

**Comment by soneal-relatient** [comment]
Is it possible to get any information on this?

**Comment by AjeetYadav07** [comment]
1. Within allergies, example allergies do not contain reactions
     a.	Allergies can optionally contain allergy reactions, which describe the adverse response to the allergic substance. 
  Reaction is capture as free text "Gastrointestinal problems, e.g., nausea, vomiting, diarrhea; &#xa;Nausea".
    b. https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/AllergyIntolerance?patient=1239620410000620
<Bundle xmlns="http://hl7.org/fhir">
    <id value="1.2.840.113619.21.1.8899560752578716278.10.1598265889976.328995"/>
    <meta>
        <lastUpdated value="2020-08-24T10:44:49.976Z"/>
    </meta>
    <type value="searchset"/>
    <total value="1"/>
    <link>
        <relation value="self"/>
        <url value="https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/AllergyIntolerance?patient=1239620410000620"/>
    </link>
    <entry>
        <fullUrl value="https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/AllergyIntolerance/1239655574000620"/>
        <resource>
            <AllergyIntolerance xmlns="http://hl7.org/fhir">
                <id value="1239655574000620"/>
                <meta>
                    <versionId value="1239655574000620"/>
                    <lastUpdated value="2010-07-07T16:10:56.870Z"/>
                    <profile value="http://hl7.org/fhir/StructureDefinition/daf-allergyintolerance"/>
                    <profile value="http://hl7.org/fhir/StructureDefinition/ge-allergyintolerance-profile.html"/>
                    <security>
                        <system value="http://www.hl7.org/fhir/v3/Confidentiality"/>
                        <code value="N"/>
                        <display value="Normal"/>
                    </security>
                    <tag>
                        <system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
                        <code value="New"/>
                        <display value="New"/>
                    </tag>
                    <tag>
                        <system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
                        <code value="Pen"/>
                        <display value="Pen"/>
                    </tag>
                    <tag>
                        <system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
                        <code value="NewPen"/>
                        <display value="New Pen"/>
                    </tag>
                </meta>
                <text>
                    <status value="generated"/>
                    <div xmlns="http://www.w3.org/1999/xhtml">
                        <table width="100%">
                            <caption>
                                <a href="Patient/1239620410000620">Patient/1239620410000620</a>
                            </caption>
                            <tbody>
                                <tr>
                                    <td width="25%">
                                        <span class="text-muted">PERCOCET (6599000220 GPI)</span>
                                    </td>
                                    <td width="8%">
                                        <span class="text-muted"> ? </span>
                                    </td>
                                    <td width="25%"> -- 
                                        <a href="Practitioner/1225652472001060">Practitioner/1225652472001060</a>
                                        <span> 2010/07/07</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </text>
                <extension url="http://hl7.org/fhir/StructureDefinition/ge-allergyintolerance-encounter">
                    <valueReference>
                        <reference value="Encounter/1239655526000620"/>
                    </valueReference>
                </extension>
                <recorder>
                    <reference value="Practitioner/1225652472001060"/>
                </recorder>
                <patient>
                    <reference value="Patient/1239620410000620"/>
                </patient>
                <substance>
                    <coding>
                        <system value="http://docs.wolterskluwercdi.com/codesystems/gpi"/>
                        <code value="6599000220"/>
                    </coding>
                    <coding>
                        <system value="http://docs.wolterskluwercdi.com/codesystems/kdc"/>
                        <code value="2152"/>
                    </coding>
                    <text value="PERCOCET"/>
                </substance>
                <status value="active"/>
                <criticality value="CRITH"/>
                <category value="medication"/>
                <note>
                    <text value="Gastrointestinal problems, e.g., nausea, vomiting, diarrhea; &#xa;Nausea"/>
                </note>
            </AllergyIntolerance>
        </resource>
        <search>
            <mode value="match"/>
        </search>
    </entry>
</Bundle>
2. Not sure how quantity works in medications.
      a.  The quantity of Ordered medications is reflected in Dosage <quantityQuantity>
<MedicationStatement xmlns="http://hl7.org/fhir">
	<patient>
		<reference value="Patient/1442678382500620"/>
	</patient>
	<informationSource>
		<reference value="Practitioner/1225652472001060"/>
	</informationSource>
	<status value="active"/>
	<effectivePeriod>
		<start value="2000-06-14T05:30:00"/>
		<end value="2100-07-14T05:30:00"/>     
	</effectivePeriod>
	<medicationReference>
		<reference value="Medication/20817"/>
		
	</medicationReference>
	<dosage>
		<text value="1 po qd"/>
		<timing>
			<repeat>
				<period value="24.00000"/>
				<periodUnits value="h"/>
			</repeat>
		</timing>
		<route>
			<coding>
				<system value="http://snomed.info/sct"/>
				<code value="26643006"/>
				<display value="Oral route"/>
			</coding>
		</route>
		<quantityQuantity>
			<value value="2.00000"/>
			<unit value="{Tablet}"/>
		</quantityQuantity>
	</dosage>
	<note value="comments"/>
	<reasonForUseReference>
        <reference value="Condition/1897891880369330"/>
    </reasonForUseReference>
</MedicationStatement>

3. Problem is defined as a condition.
4. Do not have an example of an immunization
    You will get the immunization as text "Havrix Intramuscular Suspension 720 EL U/0.5ML (83 CVX)" .
     <Bundle xmlns="http://hl7.org/fhir">
	<id value="1.2.840.113619.21.1.8899560752578716278.10.1598019493599.208542"/>
	<meta>
		<lastUpdated value="2020-08-21T08:18:13.599-06:00"/>
	</meta>
	<type value="searchset"/>
	<total value="2"/>
	<link>
		<relation value="self"/>
		<url value="https://{server}:9443/dbnameAPIServer/fhir/Immunization?patient=1442678380300620"/>
	</link>
	<entry>
		<fullUrl value="https://{server}:9443/dbnameAPIServer/fhir/Immunization/1913617086346340"/>
		<resource>
			<Immunization xmlns="http://hl7.org/fhir">
				<id value="1913617086346340"/>
				<meta>
					<versionId value="1913617086346340"/>
					<lastUpdated value="2020-08-21T08:18:06.656-06:00"/>
					<profile value="http://hl7.org/fhir/StructureDefinition/daf-immunization"/>
					<profile value="http://hl7.org/fhir/StructureDefinition/ge-immunization-profile.html"/>
					<security>
						<system value="http://www.hl7.org/fhir/v3/Confidentiality"/>
						<code value="N"/>
						<display value="Normal"/>
					</security>
					<tag>
						<system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
						<code value="New"/>
						<display value="New"/>
					</tag>
					<tag>
						<system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
						<code value="Pencil"/>
						<display value="Pencil"/>
					</tag>
					<tag>
						<system value="http://www.gehealthcare.com/fhir/codesystem/cpsemr/EditTags"/>
						<code value="NewPencil"/>
						<display value="New Pencil"/>
					</tag>
				</meta>
				<text>
					<status value="generated"/>
					<div xmlns="http://www.w3.org/1999/xhtml">
						<table width="100%">
							<caption>
								<a href="Patient/1442678380300620">Patient/1442678380300620</a>
							</caption>
							<tbody>
								<tr>
									<td width="25%">
										<span class="text-muted">Havrix Intramuscular Suspension 720 EL U/0.5ML (83 CVX)</span>
									</td>
									<td width="8%">
										<span class="text-muted">2020/08/21</span>
									</td>
									<td width="25%"> -- 
										<a 
 href="Practitioner/1225652498001060">Practitioner/1225652498001060</a>
										<span> 2020/08/21</span>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</text>
				<extension url="http://hl7.org/fhir/StructureDefinition/ge-immunization-VFCEligibility">
					<valueString value="NA"/>
				</extension>
				<identifier>
					<type>
						<coding>
							<system value="http://hl7.org/fhir/v2/0203"/>
							<code value="U"/>
							<display value="Unspecified Identifier"/>
						</coding>
						<text value="Unspecified Identifier"/>
					</type>
					<system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/ImmunizationId/Training042"/>
					<value value="1913617086346340"/>
				</identifier>
				<status value="completed">
					<extension url="http://hl7.org/fhir/StructureDefinition/ge-originalCode">
						<valueCoding>
							<system value="http://www.gehealthcare.com/fhir/cpsemr/codesystem/immunizationgivenstatus"/>
							<code value="YN"/>
							<display value="Completed"/>
						</valueCoding>
					</extension>
				</status>
				<date value="2020-08-21T08:18:06-06:00"/>
				<vaccineCode>
					<coding>
						<system value="http://hl7.org/fhir/sid/cvx"/>
						<code value="83"/>
						<display value="Havrix Intramuscular Suspension 720 EL U/0.5ML"/>
					</coding>
				</vaccineCode>
				<patient>
					<reference value="Patient/1442678380300620"/>
				</patient>
				<wasNotGiven value="false"/>
				<reported value="false"/>
				<performer>
					<reference value="Practitioner/1225652498001060"/>
				</performer>
				<encounter>
					<reference value="Encounter/1913617034346270"/>
				</encounter>
				<location>
					<reference value="Location/0"/>
				</location>
				<route>
					<text value="ncimeta "/>
				</route>
				<vaccinationProtocol>
					<doseSequence value="1"/>
					<description value="Hepatitis A"/>
				</vaccinationProtocol>
			</Immunization>
		</resource>
		<search>
			<mode value="match"/>
		</search>
	</entry>
</Bundle>
5. Can you Please try to add the Vitals, Social History and family member History by the flowsheet and or post it through the API and get the example for each and all are captured as text.
