### ISSUE TITLE
$PostPayment -  Details for Source, PaymentType, PayerType and PayerId

### ISSUE THREAD

**Issue by rahul-chetu** [virencehealth/apiserver.virencehealth.com#146]
How I can get the list of the available options for PostPayment -
- Source
- PaymentType
- PayerType 

How can I get Payer Id for a different type of Sources as Patient, Insurance etc.?
`<subject>
<reference value="Patient/1442678381950620"/>
</subject>`
I assumed 1442678381950620 as PayerId but that dont worked.

Please use the https://github.com/virencehealth/apiserver.virencehealth.com/issues/141 as reference for the previous discussion.

**Comment by Amits2070** [comment]
The payment details can be accessed through following URL

http://localhost:9080/CentricityPracticeFHIRServer/fhir/$Posting?_id=<idValue>
eg
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Posting?_id=529
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Posting?_id=527
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Posting?_id=516

This API will give you details like Payer_Id,payer_name,payer_type,payment_type

Mapping for Payment type is as below: 

1=Cash
2=Check
3=Credit\ Card
4=EFT
5=Money\ Order
6=Conveyance

Currently we are displaying numeric values. Will work later to display its description.
