### ISSUE TITLE
DocumentReference - How to properly upload/attach document to patient via API

### ISSUE THREAD

**Issue by apjardim3** [virencehealth/apiserver.virencehealth.com#149]
We are trying to upload a PDF document to the patient via the API but the CPS API doesn't seem to match up properly with the HL7 format.  We have been successful in uploading the document but not all of the settings are correct so there is a warning message that is displayed to the users when they try to access the document in addition the lower 'Notes' area of the document is empty.

We believe we have it down to the following settings that need to be properly set to get past this issue but we can't find the correct combination of the settings:

- ContentType - we've tried various combinations (text/plain, application/pdf, application/rtf, NO_REF, etc..) but they all result in a warning message when the doc is clicked on in CPS:
   - The MIMIE type for this document ({Document title displayed}) is unknown ({the ContentType we attempt to use}). The 
       document may not display correctly. Please contact the system administrator.

- DocType - We're using one of the codes from this list (http://hl7.org/fhir/valueset-c80-doc-typecodes.html) which does set the doc type in CPS.  However, the customer has a custom document type they want associated to the PDF docs we're attaching which is set in CPS Administration --> Charts --> Chart Documents --> Clinical Document Types.  How do we use the custom codes that are setup in CPS for the document type if its expecting one the HL7 doc codes?

- Format codes - we've been attempting to set the format code to see if that helps but it doesn't seem to have much of an influence. (??)

If someone could provide some guidance on the correct document API settings to upload/attach a PDF document in to a Patient's record (i.e. in the "Documents" module), that would be great.  Please advise.

**Comment by apjardim3** [comment]
We have figured out the MIME type that it is requiring.  However, we'd still like to know how to properly set some of the document settings and ultimately 'Sign' the document using the API.  The HL7 DocumentReference definition does not provide any information on the those two actions.  Is there a supplemental guide that we need to consult for those CPS type transactions?

**Comment by apjardim3** [comment]
Is this forum still active?  Can anyone confirm whether or not the following actions can be done via the API?
- Change the 'Document Type' to a custom CPS value 
- Change the 'Status' of a document to 'Signed'

If they can be modified via the API, please direct us to the documentation or provide a basic code snippet.

Screenshots of the attributes we're trying to modify:

![image](https://user-images.githubusercontent.com/59920551/89790110-73057d80-daef-11ea-9979-d2443dfc296d.png)

![image](https://user-images.githubusercontent.com/59920551/89790188-916b7900-daef-11ea-91c4-07501d84f47f.png)

**Comment by apjardim3** [comment]
Still no response?  Is there another forum that I need to post this question to?

**Comment by AjeetYadav07** [comment]
No we cannot use custom document type and change the status using DocumentReference API update operation.

**Comment by apjardim3** [comment]
Is there any plan to have full document management capability via the API?  We know that CPS v20 is being released soon, will it be available in that version?

**Comment by venkatakreddyc** [comment]
No, we don't have plans to sign the document though FHIR API. it will be with code product only. Any other document management capability, you are looking at? please let us know.

**Comment by AjeetYadav07** [comment]
Few additional points :
1. In the  POST operation of DocumentReference we can set document type when creating Chart documents (DOCUMENTTYPE entries should be present in <install_path>\jboss\standalone\deployments\DBNameAPIServer.war\WEB-INF\classes\com\gehcit\fhir\mappers\util\mappings.properties file). Note : this would be custom implementation and  will be overridden on next upgrade. Recommendation is to use hl7 recommended value sets.
2. All documents are created as unsigned because it is important for clinicians to review documents from external sources before they are signed.
3. PDFs can be attached as external attachments to Chart documents via url's. Following types of documents are supported as external attachments jpg, gif, txt, pdf, png.

**Comment by apjardim3** [comment]
Thanks for providing the additional information.  We will try the editing of the mappings.properties file to see if that will fix our issue with the custom Document Type.

 

Regards,

 

Anthony P. Jardim

Metric One, Inc.

7545 Irvine Center Dr. #200

Irvine, CA  92618

 

Direct: (949) 648-7400 x103

Fax:    (949) 877-3514

Email:  <mailto:ajardim@metricone.com> ajardim@metricone.com

 

CONFIDENTIALITY NOTICE

This email message is intended only for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law.
