### ISSUE TITLE
 CPS FHIR API: Cannot Cancel Appointments

### ISSUE THREAD

**Issue by hqkirkland** [virencehealth/apiserver.virencehealth.com#15]
**Describe the bug**
This is an operation outcome I get when I make a cancellation request:
`
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>PROCESSING</td><td>Failed to call access method</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method"
        }
    ]
}
`

**To Reproduce**
1. Make this PUT request in Postman (Raw, JSON Data):
https://pastebin.com/KaT895Bb

At this endpoint:
https://%JBoss_Hostname%:9443/%CPS_Database_Name%APIServer/fhir/Appointment/%Appointment_ID%?_format=json

**Expected behavior**
Appointment should be cancelled.

**Comment by Torin-Shepard-athena** [comment]
It is not possible to cancel appointments using the API due to an issue with one to many mappings for CPS customer-configurable appointment cancellation reasons.
It is not yet possible to map FHIR "cancelled" to a single CPS appointment cancellation choice.

**Comment by Rinkal-jain** [comment]
An extension with the CPS appointment cancellation value will be available in the V20 to make it possible to cancel appointments through Appointment PUT.
