### ISSUE TITLE
Searching DiagnosticOrder Resource by CPT Code

### ISSUE THREAD

**Issue by shayes-phreesia** [virencehealth/apiserver.virencehealth.com#150]
The specification indicates you can search the DiagnosticOrder resource by the code parameter. However, it appears that this can only be used in conjunction with the patient id? Is there any way to search for all orders by code?

**Comment by AjeetYadav07** [comment]
You can search the DiagnosticOrder resource by code but it should be in conjunction with either patient or _id.
     1. https://cpsapisandboxoAPISe.virenceaz.com:9443/demrver/fhir/DiagnosticOrder?patient=1225794135101060&code=94010
     2. https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/DiagnosticOrder?_id=1226221497001060&code=85025
There is no way to search all orders by code, this is part of design.
