### ISSUE TITLE
Practitioner search returning DoctorFacilityIDs of 0 and negative numbers

### ISSUE THREAD

**Issue by shayes-phreesia** [virencehealth/apiserver.virencehealth.com#151]
We are using the practitioner resource to pull in a list of active providers and resources to be used during setup of our integration. The API is currently returning several records with doctor facility id = 0 or some negative number. However, none of these provider records can be found in the CPS UI as either providers or users. What do these provider records correspond to and can we filter them out? 
**Provider with 0 id**
` <entry>
        <fullUrl value="http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Practitioner/1225649351001060"/>
        <resource>
            <Practitioner xmlns="http://hl7.org/fhir">
                <id value="1225649351001060"/>
                <meta>
                    <profile value="http://hl7.org/fhir/StructureDefinition/daf-practitioner"/>
                    <profile value="http://hl7.org/fhir/StructureDefinition/ge-patient-profile.html"/>
                </meta>
                <text>
                    <status value="generated"/>
                    <div xmlns="http://www.w3.org/1999/xhtml">
                        <table width="100%">
                            <tbody>
                                <tr>
                                    <td width="25%">Hanna Chen MD </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </text>
                <identifier>
                    <type>
                        <coding>
<system value="http://hl7.org/fhir/v2/0203"/>
                            <code value="PN"/>
                        </coding>
                    </type>
                    <system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/DOCTORFACILITYID/Training042"/>
                    <value value="0"/>
                </identifier>
                <active value="true"/>`

**Provider with negative id**
` <fullUrl value="http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Practitioner/-10"/>
        <resource>
            <Practitioner xmlns="http://hl7.org/fhir">
                <id value="-10"/>
                <meta>
                    <profile value="http://hl7.org/fhir/StructureDefinition/daf-practitioner"/>
                    <profile value="http://hl7.org/fhir/StructureDefinition/ge-patient-profile.html"/>
                </meta>
                <text>
                    <status value="generated"/>
                    <div xmlns="http://www.w3.org/1999/xhtml">
                        <table width="100%">
                            <tbody>
                                </tr>
                                    <td width="25%">superuser </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </text>
                <identifier>
                    <type>
                        <coding>
                            <system value="http://hl7.org/fhir/v2/0203"/>
                            <code value="PN"/>
                        </coding>
                    </type>
                     <system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/DOCTORFACILITYID/Training042"/>
                    <value value="-1009"/>
                </identifier>
                <active value="true"/>
`

**Comment by shayes-phreesia** [comment]
any updates?

**Comment by AjeetYadav07** [comment]
The Provider who is having doctor facility id = 0 or some negative number, will be filtered out in the next release.

**Comment by Torin-Shepard-athena** [comment]
Negative Practitioner.id values come from special "system" users that are required for various features with the core product such as Practitioner/-3 used to record data imported by LinkLogic.

The example given does not have "Provider with 0 id".  It has Practitioner/1225649351001060 with <id value="1225649351001060"/>.  The zero value comes from one of the Practitioner.identifiers <system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/DOCTORFACILITYID/Training042"/> <value value="0"/>

https://mydata.athenahealth.com/fhirapidoc explains the source data for Practitioner resources includes "Service Providers".  Service Providers can be marked as recipients of Test and Referral orders.  Service Providers are stored separately and have zero for the DoctorFacilityID identifier.  It is not possible to filter these out using the current API servers.

Service Providers can be viewed in Administration orange folders Codes > Charts > Service Providers.
