### ISSUE TITLE
We are unable to get the patient’s authorization code

### ISSUE THREAD

**Issue by fehsura** [virencehealth/apiserver.virencehealth.com#152]
Hi, we are using below Patient credentials but not able to get the patient’s authorization code.

User Name: Walter.caldwell@outlook.com
Password: TestPatient!@!

User Name: athenainterop@aol.com
Password: Virence@123

![Screenshot 2020-09-25 at 10 40 22 PM](https://user-images.githubusercontent.com/56104055/94296334-4e227800-ff80-11ea-998c-97ea5d8c2f80.png)

Can you please help me to get the patient’s authorization code

**Comment by KedarGanta** [comment]
Please share more details for us to provide right guidance. 
 are you trying to hit your FHIR server or using our FHIR sandbox?
          If you are using your FHIR Server, you need to complete patient API access registration step and register patients emails using B2C sign up URL.

PS: I am able to complete the patient workflow and generate auth code
 sandbox fhir server: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir 
 credentials: athenainterop@aol.com / Virence@123

**Comment by fehsura** [comment]
Hi Kedar,

We are trying to hit the FHIR sandbox with credentials: athenainterop@aol.com / Virence@123, but we are unable to get the patient’s authorization code and getting below error after redirecting. Please have a look and let me know If I miss anything.
![Uploading Screenshot 2020-09-25 at 10.40.22 PM.png…]()

**Comment by KedarGanta** [comment]
Please share your steps. If you follow the steps outlined in the developer portal you should be able to generate auth code.

**Comment by fehsura** [comment]
Here is the document that we are following for getting the code

https://mydata.athenahealth.com/access-centricity-apis

**Comment by KedarGanta** [comment]
does your URL looks this
Sample URL:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=**redirectURL**&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=**ClientIDfromDevPortal**

Please replace the bold text with details from your developer portal account. If you are still running into issues, please share the complete url by clicking on 'contact us' in the dev portal page.

**Comment by fehsura** [comment]
We are still facing the issue, please have a look into below URL:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://ensarsolutions.com/&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4wLjAiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJlNmZkZDg5NS00Y2MwLTQ2M2MtODNjZi1lZmU5NDI0NWZjYmEiLCJleHAiOjE5MTY1ODUzNDMsImNsaWVudF9uYW1lIjoiUHJvdmlkZXJBcHAiLCJpYXQiOjE2MDEwNTI1NDMsImNvbnRhY3RzIjpbImdvd3RoYW1AZW5zYXJzb2x1dGlvbnMuY29tIl0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.y2e1Bt78IJOCiimsqjTZ0lVoQqSAOtbp09LX0MX8mEi-pDEvOKZD-dFBfBX9H6qbFUd4i6Hsfw_lnPxV1zNSLE7GX0uDeIE7AW_wvCA3hvan-GmyK3-e_E-zq1ckaveq6K_Mdf8oWgFaQQgKSH955Yo0JepimwSFL_YNKdPEWsw

**Comment by fehsura** [comment]
Hi Kedar,

email delivery failed, when I am trying to send the details to athenainterop@athenahealth.com 

![image](https://user-images.githubusercontent.com/56104055/94337649-d13be080-0009-11eb-9bed-aff96c3d1dab.png)

**Comment by KedarGanta** [comment]
@fehsura  I believe there is an issue in your code. The authcode is generated by the sandbox for the given patient id
You can update the URL with the string &response_mode=query to get authcode as a query parameter. 
refer to the parameter code in this example URL: https://ensarsolutions.com/?**code**=eyJraWQiOiJjcGltY29y

try this URL to test authcode generation:
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://ensarsolutions.com/&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4wLjAiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJlNmZkZDg5NS00Y2MwLTQ2M2MtODNjZi1lZmU5NDI0NWZjYmEiLCJleHAiOjE5MTY1ODUzNDMsImNsaWVudF9uYW1lIjoiUHJvdmlkZXJBcHAiLCJpYXQiOjE2MDEwNTI1NDMsImNvbnRhY3RzIjpbImdvd3RoYW1AZW5zYXJzb2x1dGlvbnMuY29tIl0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.y2e1Bt78IJOCiimsqjTZ0lVoQqSAOtbp09LX0MX8mEi-pDEvOKZD-dFBfBX9H6qbFUd4i6Hsfw_lnPxV1zNSLE7GX0uDeIE7AW_wvCA3hvan-GmyK3-e_E-zq1ckaveq6K_Mdf8oWgFaQQgKSH955Yo0JepimwSFL_YNKdPEWsw&response_mode=query
