### ISSUE TITLE
Invalid client error when accessing the sandbox environment

### ISSUE THREAD

**Issue by royyin224** [virencehealth/apiserver.virencehealth.com#154]
We have developed an application that works with API and it is already in production environment with no issues. Though, recently we are back to develop new project at sandbox environment, the same process to retrieve auth_code doesn't seem to work anymore, is there any change to this process or are we missing anything? Below is our constructed url for Access My Data URL:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?client_id=[CLIENT_ID]&state=[OUR_CUSTOM_GENERATED_STATE]&redirect_uri=[REDIRECT_URL_REGISTERED_IN_DEVELOPER_CENTRAL]&response_type=code%20id_token&response_mode=form_post&aud=https%3a%2f%2fcpsapisandbox.virenceaz.com%3a9443%2fdemoAPIServer%2ffhir&scope=openid+profile+offline_access+user%2f*.*

In our application, when accessing this URL, it returns back "https://d6d8193d8f94.ngrok.io/ge_api/virence/auth_token?error=invalid_client&error_description=Unknown%20client" and "The requested resource does not support http method 'GET'.", I suppose this is because our endpoint only expects a POST request with auth_code, do we need to support the GET request too?

Note, our development environment uses ngrok (https://ngrok.com/) to provide endpoint for redirect url.

**Comment by AjeetYadav07** [comment]
Construct Access My Data URL like below :
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri={REDIRECT_URL}&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}.
Please follow the detail steps mention in the link https://mydata.athenahealth.com/access-centricity-apis for API access.

**Comment by royyin224** [comment]
After testing in different environments, the same application runs fine at US IP but part of our dev team is not in US and the application doesn't work at their environment, can this be the limitation?

**Comment by jdkizer9** [comment]
I'm getting a similar error. Is there a time delay associated with registration?

**Comment by AjeetYadav07** [comment]
Hi Roy,
we do not enforce any IP restrictions to access FHIR API endpoints. It is up to the customer who can decide on applying IP restrictions to their network. 
I think you are using the same Client Id for the new App.  Please check whether client Id is generated using the redirect URI given in the Access My Data URL or Try to create/register new app and follow link https://mydata.athenahealth.com/access-centricity-apis.

**Comment by royyin224** [comment]
Hi AjeetYadav07,

thanks for your reply, though even after we double checked the cliend ID/secrect/redirect URI, the error persists, below are our request to start retrieving the auth token process

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?client_id=[...]SVYFsxYsvDM25MWSbYXUTrUbmKv4WMEKfp4NubPCLaljRnOs&state=defaultState&redirect_uri=https%3a%2f%2f[...]3350c.ngrok.io%2fge_api%2fvirence%2fauth_token&response_type=code%20id_token&response_mode=form_post&aud=https%3a%2f%2fcpsapisandbox.virenceaz.com%3a9443%2fdemoAPIServer%2ffhir&scope=openid+profile+offline_access+user%2f*.*

and this is how it is configured at developer portal

![Screenshot 2020-10-26 143942](https://user-images.githubusercontent.com/9049754/97141487-c5bf0f00-1799-11eb-8549-cb9a387bdfe0.png)

as you can see, the redirect URI and client ID are the same, yet this is how it returns

https://[...]3350c.ngrok.io/ge_api/virence/auth_token?error=invalid_client&error_description=Unknown%20client

is there any other configuration that I should be checking?

**Comment by Torin-Shepard-athena** [comment]
Please re-register your application(s) to get new client id and try again.

**Comment by royyin224** [comment]
@Torin-Shepard-athena thanks for your help, after re-register our application, it finally worked, I am closing the issue.
