### ISSUE TITLE
Invalid Client

### ISSUE THREAD

**Issue by fehsura** [virencehealth/apiserver.virencehealth.com#155]
Hi AthenaHealth,

We have created an application in the Athena Health Developer portal. We are getting an issue while executing the below URL for getting code. Can you please check and let me know if we miss anything. 

Thanks in Advance

![image](https://user-images.githubusercontent.com/56104055/96338856-6b91c000-10ae-11eb-8079-1e2667ca0ea0.png)

**Comment by fehsura** [comment]
URL: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://ensarsolutions.com/

&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2Vuc2Fyc29sdXRpb25zLmNvbVwvIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4xLjEiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJhYjNlNmE1Zi04NzgyLTQyN2QtYTlmYS1kNGExYmViNTRiODgiLCJleHAiOjE5MTgzOTk2MTksImNsaWVudF9uYW1lIjoiTVJDRW5zYXIiLCJpYXQiOjE2MDI4NjY4MTksImNvbnRhY3RzIjpbImdvd3RoYW1AZW5zYXJzb2x1dGlvbnMuY29tIl0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.ND31auTzhhxBtUlo3PALC7ti3ROa0ljuI_wvUo7xQHQI3bm5dKZvpp3hG3A2mbo9Ue70_NLTSe7WNbKHEC95wDq-muNXdouzOsRzKMLWcoQ0HpEecLXCP0H3tC592oxK1ig-uXmfOeYmGnSkew2BlIXuDK2ZBunv01ieQw2Paao

**Comment by jdkizer9** [comment]
I'm getting the same issue. Have you made any progress?

**Comment by AjeetYadav07** [comment]
@fehsura, Are you using same Client Id for the new App? Please check whether client Id is generated using the redirect URI given in the Access My Data URL or Try to create/register new app and follow link https://mydata.athenahealth.com/access-centricity-apis to get the auth_code.

**Comment by Torin-Shepard-athena** [comment]
Please re-register your application(s) to get new client id and try again.
