### ISSUE TITLE
Is the aud parameter correct?

### ISSUE THREAD

**Issue by jdkizer9** [virencehealth/apiserver.virencehealth.com#156]
Per the SMART App Launch framework, the `aud` parameter should be set to "URL of the EHR resource server from which the app wishes to retrieve FHIR data". The developer documentation suggest that the `aud` parameter be set to `https://cpsapisandbox.virenceaz.com:9443/demoAPIServer`. However, the location of the metadata resource is [`https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata`](https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata), which suggests that the URL of the EHR resource server is actually `https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir`. Which is correct?

**Comment by AjeetYadav07** [comment]
To access the fhir API inorder to retrieve FHIR data use below URL :
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir with /Resource_name/searchcriteria=searchvalue

**Comment by jdkizer9** [comment]
@AjeetYadav07 sorry that my original question was unclear. I'm referring to the `aud` parameter passed as part of the authorization request as defined in [this section](http://hl7.org/fhir/smart-app-launch/#step-1-app-asks-for-authorization) of the SMART App Launch framework.

**Comment by raviranjank256** [comment]
@jdkizer9 The correct value for 'aud' parameter is actually 'https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir'.
It will be updated in the developer documentation in the next release, we have a work item for the same.
