### ISSUE TITLE
Server error when processing redirect

### ISSUE THREAD

**Issue by jdkizer9** [virencehealth/apiserver.virencehealth.com#157]
I'm getting a server error after logging in during the authorization flow. The url is `https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize-callback`. The stack trace is in the attached screenshot.

My client ID is `eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL3d3dy5jb21tb25oZWFsdGgub3JnXC8iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvYXBwZGV2LnRjcGRldi5vcmdcL21cL3Boclwvb2F1dGhcL3JlZGlyZWN0Il0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMC40LjciLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiIwMDYwN2M2MC1iOWM4LTQzNjgtYTMzYS03M2Q5MjBhMTVmNzciLCJleHAiOjE5MTkyODczMzEsImNsaWVudF9uYW1lIjoiQ29tbW9uSGVhbHRoIERldiIsImlhdCI6MTYwMzc1NDUzMSwiY29udGFjdHMiOlsiamFtZXNAdGhlY29tbW9uc3Byb2plY3Qub3JnIl0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.XgcbdE5yoS2hZUyD30dvoaRaCL7b3ViGAkFtBpwHJSuo4PuzmdHtW1cGPFEdIRY44X_Ul-Kz9qPpSboijigvVR4Qhi8gRteHTv8TWHwZCq6GAJOIaZq7KphtkLD6LsHUDok-HqY0unYnlvNqFFpYeAjIiI65ui4tiqgrrMLaW3U`.

![Screenshot_1603755248](https://user-images.githubusercontent.com/6721921/97239548-7d135000-17b1-11eb-92f3-ab83fb47de3f.png)

**Comment by jdkizer9** [comment]
Following up on this, I was able to successfully authenticate using the sample app. However, when modifying the code to change the `response_type` parameter to code (instead of `code%20id_token`), the above error is thrown. Note that per the [SMART App Launch framework](http://hl7.org/fhir/smart-app-launch/#step-1-app-asks-for-authorization), the `response_type` parameter should be `code`.

**Comment by Torin-Shepard-athena** [comment]
We agree with your conclusion: Any SMART on FHIR app should be able to call FHIR Server authorize endpoint with only code as value for response_type parameter.

Our implementation incorrectly requires both code and id_token for response_type parameter.  Part of the reason for this is that we use id_token from Microsoft AAD to get the identity of the authenticated user.

We will consider removing id_token as a requirement for response_type parameter in a future release.

**Comment by jdkizer9** [comment]
Thanks @Torin-Shepard-athena. Do you have a sense for when this requirement will be removed?

**Comment by KedarGanta** [comment]
@jdkizer9 FYI... The fix would be made available in the next release 2021.
