### ISSUE TITLE
Observation resource route does not support the `patient` parameter

### ISSUE THREAD

**Issue by jdkizer9** [virencehealth/apiserver.virencehealth.com#160]
Per the Argonaut Data Query Implementation Guide [Lab Results](http://www.fhir.org/guides/argonaut/r2/StructureDefinition-argo-observationresults.html) and [Clinical Vitals](http://www.fhir.org/guides/argonaut/r2/StructureDefinition-argo-vitalsigns.html) profiles, the `Observation` resource route should support the `patient` query parameter. However, when specifying the `patient` parameter instead of the `subject` parameter, I get the following response:

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>BUSINESSRULE</td><td>Either subject or _id must be specified in the query</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Either subject or _id must be specified in the query"
        }
    ]
}
```

**Comment by AjeetYadav07** [comment]
As per our implementation of DSTU2, For Observation resource **patient** is not supported as mandatory search parameter. In the next release we are providing the support for it.

**Comment by jdkizer9** [comment]
Hi @AjeetYadav07,  Is the `patient` parameter supported yet? This is currently blocking us
