### ISSUE TITLE
DiagnosticReport resources not supported

### ISSUE THREAD

**Issue by jdkizer9** [virencehealth/apiserver.virencehealth.com#161]
The Argonaut Data Query Implementation Guide includes the [DiagnosticReport](http://www.fhir.org/guides/argonaut/r2/StructureDefinition-argo-diagnosticreport.html) profile for laboratory results. However, when querying for DiagnosticReports, I get the following output:

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>PROCESSING</td><td>Unknown resource type 'DiagnosticReport' - Server knows how to handle: [Appointment, ReferralRequest, Organization, AllergyIntolerance, CarePlan, FamilyMemberHistory, Goal, StructureDefinition, Medication, Encounter, Procedure, AuditEvent, List, MedicationOrder, ConceptMap, ValueSet, OperationDefinition, DocumentReference, Condition, Immunization, Device, DiagnosticOrder, Patient, ProcedureRequest, Coverage, RelatedPerson, Practitioner, NamingSystem, Schedule, Observation, MedicationAdministration, Slot, Binary, MedicationStatement, Location]</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Unknown resource type 'DiagnosticReport' - Server knows how to handle: [Appointment, ReferralRequest, Organization, AllergyIntolerance, CarePlan, FamilyMemberHistory, Goal, StructureDefinition, Medication, Encounter, Procedure, AuditEvent, List, MedicationOrder, ConceptMap, ValueSet, OperationDefinition, DocumentReference, Condition, Immunization, Device, DiagnosticOrder, Patient, ProcedureRequest, Coverage, RelatedPerson, Practitioner, NamingSystem, Schedule, Observation, MedicationAdministration, Slot, Binary, MedicationStatement, Location]"
        }
    ]
}
```

**Comment by AjeetYadav07** [comment]
**DiagnosticReport** resource is not supported as per DSTU2  implementation, supported resources are listed here:
[Appointment, ReferralRequest, Organization, AllergyIntolerance, CarePlan, FamilyMemberHistory, Goal, StructureDefinition, Medication, Encounter, Procedure, AuditEvent, List, MedicationOrder, ConceptMap, ValueSet, OperationDefinition, DocumentReference, Condition, Immunization, Device, DiagnosticOrder, Patient, ProcedureRequest, Coverage, RelatedPerson, Practitioner, NamingSystem, Schedule, Observation, MedicationAdministration, Slot, Binary, MedicationStatement, Location]

**Comment by rashmi1977** [comment]
This Functionality will be available in future releases. As we do not intend to support this resource as part of DSTU2 and we have new version of FHIR R4 implemented as part of our future release. This functionality will be available as part of future releases
