### ISSUE TITLE
Is FHIR Required?

### ISSUE THREAD

**Issue by NWHSU** [virencehealth/apiserver.virencehealth.com#162]
Hello:

This post basically is asking questions about the FHIR API server. It is a bit long, so bear with me because I need to give some background info.

Our institution is Northwestern Health Sciences University in Bloomington, MN. The University trains students in chiropractic, acupunture/oriental medicine, massage therapy, nutrition services, x-ray tech, and some undergraduate health disciplines. We have 3 on-site clinics which serve both students and the public, and are also used for training students as interns. In other words, we are not the typical Athena customer who is a regular medical clinic or in a hospital setting. We are an educational institution that has had Centricity for many years in our clinics and is used to train students in proper charting methods. We currently have Centricity Practice Management v12.3.3.

The v20 upgrade manual says that the FHIR API server does these things:

-  Prescribing medications through the new Medication Management module.
-  Appropriate Use Criteria (AUC) checking for orders.
-  Generating CCDA 2.1 documents.
-  Patient Electronic Access to Their Health Information.
-  C-Now, a new application that allows providers to access patient information from anywhere.

Because of our uniqueness, we will not be doing any of these things. We are not licensed to prescribe medications, we are not required to use AUC, we do not use CCDA documents, we do not have a patient portal at this time, and do not plan to use C-Now, although C-Now might be "nice" in the future, but so far providers we have asked do not see a need for it.

Given the above:
1.  Do we have to install and configure the FHIR API server if we are not going to use it? Will not installing it hinder other parts of v20 from working that are not related to the 5 bulleted items above?

2. If we do have to install it, then:

    The install procedures seem to imply that when the AAD connected apps are created, they will be connected to one database      only. Is this true? This is a concern because we have 4 Centricity environments with 4 separate databases: Development, Test, Production and Student Training. If FHIR locked down to only one environment, should it only be installed on Production to avoid any potential conflicts with other environments?

Thanks in advance for any insights anyone can provide on how to proceed.

**Comment by AjeetYadav07** [comment]
Both the options are available in v20 upgrade
1. If you do not  install and configure the FHIR API server, Still you will be able to access the features except v20 related 
    features mentioned in 5 bulleted items above.
2. if you install and configure the FHIR API Server, then:
      1. don't do the onboarding ( running b2b script).
      2. Installation of FHIR API Server needs to connect single database and functionality of that database only 
          accessible.

**Comment by NWHSU** [comment]
Thank you for your reply. I really appreciate the clarification about the FHIT API server.

Bill Johnson, Ph.D.
Senior IT Consultant

Northwestern Health Sciences University
2501 W. 84th St., Bloomington, MN 55431
P 952-885-5425 OR 952-888-4777 x 247
www.nwhealth.edu<http://www.nwhealth.edu/>

[cid:image002.png@01D6D3B1.6892C690]
