### ISSUE TITLE
Is CDA retrieval and wrapping in CDA header supported in athenaPractice v12 or above?

### ISSUE THREAD

**Issue by koldune** [virencehealth/apiserver.virencehealth.com#163]
I'm testing against a database on build 12.3.0.2242. I've successfully retrieved a CCD document part using the resource /DocumentReference/$generate and decoded the base64 encoded content data as XML. I observed that the content is only a CCD part, it does not have the encompassing elements of patient and practice as a header component. I reason that the /DocumentReference/$convert-cda resource is meant to retrieve that data however I do not see precisely how, and the calls I've been making are leading me to believe the resource is not available in the current FHIR API endpoint.
Example call:
URL: https://dts-qts17:9443/cpsv20_demoAPIServer/fhir/DocumentReference/$convert-cda?conformance=CCDA2.1&contentType=text/plain
Outcome:
Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[DocumentReference/$convert-cda] with parameters [[conformance, contentType]]

1. Is this $convert-cda supported and expected to work?
2. Is the structure of the call being made above an accurately constructed call that should work assuming the FHIR endpoint is properly configured?
3. Is the $convert-cda call the appropriate method for retrieving a CDA wrapper that can be prepended or otherwise integrated with the CDA response part from the $generate call? If not, what methods should be used to get a complete CDA using the FHIR endpoint?

**Comment by AjeetYadav07** [comment]
To retrieve a CCD document we are using the resource/DocumentReference/$generate only, there is no $convert-cda supported for this. The encompassing elements of patient and practice as a header component is available from 12.3.3 version which you can see in below snapshot: 
![image](https://user-images.githubusercontent.com/68940876/102795775-49306180-43d3-11eb-8cd7-dac71dd24df7.png)
![image](https://user-images.githubusercontent.com/68940876/102795981-90b6ed80-43d3-11eb-8ee5-8962cc2ca7c4.png)

**Comment by koldune** [comment]
Thank you, after reviewing your reply I went back and re-examined the xml that was being generated and found that the elements were sort of hidden in the first line of output. Somehow the CCD body is formatting the elements visually in a "prettified" manner and the header elements are all in one line as the top and so what I was looking for was outside the visible area. Simple mistake on my part. Consider this closed.
