### ISSUE TITLE
Access provisioning for FHIR APIs

### ISSUE THREAD

**Issue by poojajagtap2301** [virencehealth/apiserver.virencehealth.com#164]
How do we provision access to FHIR APIs for a requirement where we need to get a list of all patients and their other relevant FHIR resources like Observation, etc.
We have tried to follow the API access documentation but it only talks about a single patient data get. 
When we use the Provider workflow to generate an authorization code, on click on Select Patient we are getting error: Oops!
session_expired or invalid_state
Your session timed out or the authorization request was invalid. 

To fulfil the requirement we need a mechanism to call the FHIR API and get all available resources into our application as read only, is there a way to do this?

Thanks

**Comment by AjeetYadav07** [comment]
Can you provide more information from error logs for "When we use the Provider workflow to generate an authorization code, on click on Select Patient we are getting error: Oops!
session_expired or invalid_state
Your session timed out or the authorization request was invalid" if it is not sensitive?

**Comment by poojajagtap2301** [comment]
We dont have access to logs of developer portal. Please find attached screeentshot for your reference.


![image](https://user-images.githubusercontent.com/23481177/102891623-8412b380-442c-11eb-9878-32de1a8d176b.png)

**Comment by poojajagtap2301** [comment]
We are trying steps on this page and we are getting above error at step Generate an authorization code.

![image](https://user-images.githubusercontent.com/23481177/102896916-2afb4d80-4435-11eb-8f4c-06e917e1588b.png)

**Comment by AjeetYadav07** [comment]
Instead of patient workflow, please consider using provider workflow.https://mydata.athenahealth.com/access-the-apis has details about Provider workflow authorization flow. We have tried by creating new application and getting the auth code. Please recheck the steps mentioned in above link and review https://mydata.athenahealth.com/fhirapidoc API resource definitions > Overview > Security talks about system login that may support your needs.

**Comment by poojajagtap2301** [comment]
still the same issue. we are passing following parameters for getting auth code. Please suggest.

![image](https://user-images.githubusercontent.com/23481177/103280328-220efc80-499e-11eb-93f3-c7b490ea26ac.png)

**Comment by AjeetYadav07** [comment]
Hi,  Follow developer portal guide, Login to  https://mydata.athenahealth.com/my-apps, register an application with REDIRECT_URL  which generates a CLIENT_ID. Construct the Access My Data URL which look like:
"https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20user/*.read&response_type=code%20id_token&response_mode=query&redirect_uri=<REDIRECT_URL>&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=<CLIENT_ID >". 

Please replace <REDIRECT_URL> with Redirect URLs used in registration of application and also replace <CLIENT_ID> with generated Client ID. Open the constructed url in browser to get the auth code. Further steps  are outlined in the dev portal page.

**Comment by AjeetYadav07** [comment]
As we have not received any further communication related to this issue, we are closing the same.
