### ISSUE TITLE
Use refresh_token to get access_token

### ISSUE THREAD

**Issue by greenbutton75** [virencehealth/apiserver.virencehealth.com#167]
Is there a way to get rid of https://login.microsoftonline.com/ login window 
so that user credentials entered programmatically?

And one more question - I was able to get refresh_token with "offline_access"
Please advice how can I use it to get new access_token.
I get this error "The request sent by the client was syntactically incorrect"

![image](https://user-images.githubusercontent.com/36859844/105364566-e3cccc00-5c2f-11eb-9f5e-a0ac5de03ce5.png)

**Comment by AjeetYadav07** [comment]
Please look at the metadata Conformance statement to bypass the https://login.microsoftonline.com/ login window by entering  user credentials programmatically.

Follow the below steps to get new access token from refresh token :
1. Generate the refresh token with the help of code.
![refresh_token1](https://user-images.githubusercontent.com/68940876/105989142-b3b97900-60c6-11eb-9e3a-d3cf7637dbfc.jpg)
2. In response you will get one refresh token and copy it.
![refresh_token2](https://user-images.githubusercontent.com/68940876/105989147-b5833c80-60c6-11eb-8e39-711fbe7587cf.jpg)
3. Modify the body like below and paste the refresh token which you copied in step 2 and post the request. 
![refresh_token3](https://user-images.githubusercontent.com/68940876/105989155-b7e59680-60c6-11eb-87eb-7bd2c86e4584.jpg)
4. In the response you will see one access token and one refresh token. if further you want to create refresh token then copy the refresh token from here and follow step 3.
![refresh_token4](https://user-images.githubusercontent.com/68940876/105989161-ba47f080-60c6-11eb-8b58-ccd39ff17e3a.jpg)

**Comment by ARCSIndia** [comment]
> Please look at the metadata Conformance statement to bypass the https://login.microsoftonline.com/ login window by entering user credentials programmatically.
> 
> Follow the below steps to get new access token from refresh token :
> 
> 1. Generate the refresh token with the help of code.
>    ![refresh_token1](https://user-images.githubusercontent.com/68940876/105989142-b3b97900-60c6-11eb-9e3a-d3cf7637dbfc.jpg)
> 2. In response you will get one refresh token and copy it.
>    ![refresh_token2](https://user-images.githubusercontent.com/68940876/105989147-b5833c80-60c6-11eb-8e39-711fbe7587cf.jpg)
> 3. Modify the body like below and paste the refresh token which you copied in step 2 and post the request.
>    ![refresh_token3](https://user-images.githubusercontent.com/68940876/105989155-b7e59680-60c6-11eb-87eb-7bd2c86e4584.jpg)
> 4. In the response you will see one access token and one refresh token. if further you want to create refresh token then copy the refresh token from here and follow step 3.
>    ![refresh_token4](https://user-images.githubusercontent.com/68940876/105989161-ba47f080-60c6-11eb-8b58-ccd39ff17e3a.jpg)

I have tried to generate refresh_token using Patient/Provider workflow.Access_token generated but there is no refresh_token returned on response. Please suggest the changes I have to done to achieve.
![Token_Response](https://user-images.githubusercontent.com/52694390/109286733-a66be780-7848-11eb-863c-40ed157e30fe.png)

**Comment by ARCSIndia** [comment]
I have tried to generate refresh_token using Patient/Provider workflow.Access_token generated but there is no refresh_token returned on response. Please suggest the changes I have to done to achieve.
![Token_Response](https://user-images.githubusercontent.com/52694390/109287164-40cc2b00-7849-11eb-854d-da83fd1bb9b3.png)

**Comment by AjeetYadav07** [comment]
Please check the access my data url. Construct the url with offline_access like below:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri={REDIRECT_URL}&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}
