### ISSUE TITLE
Demo Account - invalid_request error

### ISSUE THREAD

**Issue by nerdyworm** [virencehealth/apiserver.virencehealth.com#169]
Good Afternoon,

When trying to login via the Centricty Token Generation example included in this repo with the demo user hwinston@sboxprovtenant.com, the sandbox server eventually responds with the following:

```
invalid_request

An invalid authorization request was received. Please retry the login.
```
Url of message: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize-callback

Trying my newly registered account yields a different error from the microsoft login:

```
AADSTS50020: User account '<my email address>' from identity provider 'live.com' does not exist in tenant 'FHIR Sandbox - Provider Access' and cannot access the application '45e8ea72-5bff-423e-b5a2-2dfc2b651f7b'(GE Healthcare API Server) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
```

Any help would be appreciated,
Thanks!

**Comment by saravanakumargs** [comment]
I am also getting the same error after providing the username and password.

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient&response_type=code%20id_token&redirect_uri=https://localhost:8080/emrlogin/athenaLoginSuccess&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=clientid

**Comment by AjeetYadav07** [comment]
Please try it now... working as expected
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20user/*.read&response_type=code%20id_token&response_mode=query&redirect_uri=https://httpbin.org/anything&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}

**Comment by nerdyworm** [comment]
Looks like it's working now!  Thanks!
