### ISSUE TITLE
invalid_client error for new apps in sandbox

### ISSUE THREAD

**Issue by dwwinters** [virencehealth/apiserver.virencehealth.com#171]
**Describe the bug**
Followed the instructions on registering a new provider-facing app here: https://mydata.athenahealth.com/access-the-apis
It worked the first time but now newly created apps return an invalid_client error.

**To Reproduce**
1. Create a new app in the developer portal
2. Generate url using client_id and redirect_url
3. Go to that url
4. Sandbox redirects to app with an invalid_client query parameter

**Expected behavior**
This mostly worked the first time I followed the instructions.  The constructed url brought me to page to select either a Personal or Work account.  Selecting "work" I was brought to a patient selector.  I selected a patient but realized I needed to modify my redirect url for my app.  Deleted the app in the developer portal and started over.  Tried a couple times and each new app results in the above behavior where the sandbox returns an invalid client id error.  What's especially odd is that the first url I generated still works even though I deleted the corresponding app in the portal.

**Screenshots**
n/a

**Desktop (please complete the following information, if applicable):**
 - OS: MacOS
 - Browser Chrome
 - Version 88.0.4324.150 

**Smartphone (please complete the following information, if applicable):**
n/a

**Additional context**
n/a

**Comment by dwwinters** [comment]
What appear to be related issues: #154 #155 

I've tried the solution of recreating the client in the developer portal to no avail.  It appears for those other issues the users had to wait days for things to start working again.  Wondering if there isn't caching going on with the sandbox?

**Comment by AjeetYadav07** [comment]
I've tried the same workflow, register a new application in dev portal -> construct access my data url and generate the access token from provider workflow but not getting any issue.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient&response_type=code%20id_token&redirect_uri=https://httpbin.org/anything&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}.
can you share the constructed access my data URL?

**Comment by dwwinters** [comment]
Trying again, this time using the `token-generation-sample-code`, I was able to successfully authenticate to the sandbox.
