### ISSUE TITLE
Practiotioner's service-types (or Appointment types)

### ISSUE THREAD

**Issue by eluchetti** [virencehealth/apiserver.virencehealth.com#19]
**Your question**

How do I request the list of a Practitioner's bookable appointments type?
thanks very much in advance

Emanuele Luchetti

**Comment by keithboone** [comment]
You can use the ValueSet API<https://mydata.gehealthcare.com/static/apidoc/ig-ge-valueset.html> to access those codes.

You can access them using ValueSet/C80APPOINTMENTTYPECPS and ValueSet/C80APPOINTMENTTYPEEMR

                Keith

**Comment by eluchetti** [comment]
That is ... wow , thanks!
it doesn't seem like something which can be used to specify the actual appointment type in the appointment booking process. We are trying to enable appointment booking from our application so we need to know the actual bookable type of appointment which can be booked for each practitioner. is this something that you @keithboone or anybody can help us with?
thanks in advance

**Comment by keithboone** [comment]
There’s a separae API coming for the Server to support this.  More details to be posted in the future on that.

On Oct 10, 2018, at 5:49 AM, eluchetti <notifications@github.com<mailto:notifications@github.com>> wrote:


That is ... wow , thanks!
it doesn't seem like something which can be used to specify the actual appointment type in the appointment booking process. We are trying to enable appointment booking from our application so we need to know the actual bookable type of appointment which can be booked for each practitioner. is this something that you @keithboone<https://github.com/keithboone> or anybody can help us with?
thanks in advance

**Comment by eluchetti** [comment]
Hello Keith, 
sorry to bother you....

> There’s a separae API coming for the Server to support this.  More details to be posted in the future on that.

I have some questions about that
1. do you mean "separate" from CPS's FHIR interface?
2. can you forecast when this separate will be available? 
3. do you foresee some workaround to implement online appointment by selecting appointmenttype?

thanks very much in advance
emanuele Luchetti

**Comment by keithboone** [comment]
A different FHIR operation will be available.

In the next release (V18), I don’t determine release dates ;-) but surely in next few months.  Members of the parter program have access to more information channels than I can make available here.  Talk to your parter program contact for details.

I feel a post coming on for the last in github wiki, when I get a chance.

On Oct 10, 2018, at 8:55 PM, eluchetti <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Keith,
sorry to bother you....

There’s a separae API coming for the Server to support this. More details to be posted in the future on that.

I have some questions about that

  1.  do you mean "separate" from CPS's FHIR interface?
  2.  can you forecast when this separate will be available?
  3.  do you foresee some workaround to implement online appointment by selecting appointmenttype?

thanks very much in advance
emanuele Luchetti
