### ISSUE TITLE
Practitioner's Schedules and slots

### ISSUE THREAD

**Issue by eluchetti** [virencehealth/apiserver.virencehealth.com#20]
**Your question**

I'v been trying to test schedules by searching for a practitioner's schedules https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Schedule?_format=json&actor=Practitioner/1736425520011410 

but there doesn't seem to be any practitioner with a schedule defined

am I doing correctly?
is there any possibility to have at least one schedule defined so to be able to test it?
thanks in advance

**Comment by eluchetti** [comment]
I'm trying to follow CPS's FHIR documentation for implementing online booking https://www.hl7.org/fhir/appointment.html#basic-workflow

**Comment by Torin-Shepard-athena** [comment]
The :missing modifier can be in this context The following query will return a Bundle of Schedule resources with references to Practitioners that have schedules defined in the CPS API Sandbox.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Schedule?actor:missing=false

You can search Slot resource by schedule parameter to get slots in a given Schedule.id
