### ISSUE TITLE
has anybody successfully implemented the appointment booking workflow on FHIR? 

### ISSUE THREAD

**Issue by eluchetti** [virencehealth/apiserver.virencehealth.com#21]
**Your question**

Hello, we're having some hard times at obtaining some important informations about implementing the booking process over FHIR. 
We are in disposition of trying hard but it would be very valuable at least to understand if cases of success currently  exist.
Does anybody know this?
thanks in advance

**Comment by eluchetti** [comment]
I guess that's a NO! 
new answer, I have been told that as of now the FHIR interface is "readonly" while de https://mydata.gehealthcare.com/fhirapidoc states it is not: 

> Create operations are executed as specified in the HL7 FHIR search operation definition. To create a new Appointment resource, an application must perform an HTTP POST, specifying the content of the resource in the body of the request.

`POST [base]/fhir/Appointment?{_format=[json|xml]}`

can someone clarify this?

thanks in advance

**Comment by keithboone** [comment]
It is read/write for appointments.  We’ll see if we can get you an example post request from one of our environments.

On Oct 23, 2018, at 1:52 AM, eluchetti <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess that's a NO!
new answer, I have been told that as of now the FHIR interface is "readonly" while de https://mydata.gehealthcare.com/fhirapidoc states it is not:

Create operations are executed as specified in the HL7 FHIR search operation definition. To create a new Appointment resource, an application must perform an HTTP POST, specifying the content of the resource in the body of the request.

POST [base]/fhir/Appointment?{_format=[json|xml]}

can someone clarify this?

thanks in advance

**Comment by redshirtrob** [comment]
Did anything ever happen here? I've been trying to book an appointment in the demo environment, but I can't seem to specify the "Location" participant, despite the fact I'm including it in the participant list. I'd love to see an example for the demo environment.

**Comment by ychowdhary** [comment]
POST [base]/fhir/Appointment
Sample XML Payload

```
<Appointment xmlns="http://hl7.org/fhir">
    <status value="pending"/>
    <start value="2009-07-07T06:45:00.000Z"/>
    <end value="2009-07-07T07:00:00.000Z"/>
    <minutesDuration value="15"/>
    <participant>
        <actor>
            <reference value="Patient/1442678385700620"/>
        </actor>
    </participant>
    <participant>
        <type>
            <coding>
                <system value="http://hl7.org/fhir/v3/ParticipationType"/>
                <code value="PPRF"/>
                <display value="primary performer"/>
            </coding>
            <text value="primary performer"/>
        </type>
        <type>
            <coding>
                <system value="http://hl7.org/fhir/ValueSet/c80-practice-codes"/>
                <code value="394601005"/>
                <display value="Physical Therapy"/>
            </coding>
            <text value="Physical Therapy"/>
        </type>
        <actor>
            <reference value="Practitioner/1588761792000070"/>
        </actor>
    </participant>
    <participant>
        <actor>
            <reference value="Location/FAC-3"/>
        </actor>
    </participant>
    <participant>
        <type>
            <coding>
                <system value="http://www.gehealthcare.com/fhir/cpsemr/codesystem/PARTICIPANTTYPECPS"/>
                <code value="Resource"/>
                <display value="Resource"/>
            </coding>
            <text value="Resource"/>
        </type>
        <actor>
            <reference value="Practitioner/1588761792000070"/>
        </actor>
    </participant>
</Appointment>
```
