### ISSUE TITLE
wha's the real server url not the sandbox url?

### ISSUE THREAD

**Issue by wycarol44** [virencehealth/apiserver.virencehealth.com#24]
I read through the documents, https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?
 is the sample url to work with, butI don't know what's the real (live) server url with real data.

I am able to get the access token after authorizing the test account on sandbox server, pull test data with the token. but I read through the doc and couldn't find the real server url. Can anyone help me with that?

Thanks a lot!

**Comment by SameerSingh1991** [comment]
Do you have a configured and working on premise FHIR server.

**Comment by SameerSingh1991** [comment]
Marking this issue as closed. Please reopen if you still face any issues.
