### ISSUE TITLE
Receving API Token from API Call

### ISSUE THREAD

**Issue by pri13** [virencehealth/apiserver.virencehealth.com#26]
HI All,

We are trying to leverage the GE API's to query (read/write) GE CPS through our application.  Based on the documentation, we should be using the Application Service method but do not see any documentation on how the actually get the token code.  
We have registered our App within the Developer Portal, so we have the ClientID and ClientSecret.  We are able to perform the Provider workflow without any issues but since we are wanting to do something similar directly through our application that does not have any UI (frontend) to it, how do we accomplish this?
The following is a very simple use case that we are wanting to solve for:  A patient has an appointment for which we have received a confirmation that the patient will be keeping that appointment or cancelling the appointment.  I have all the context of the patient and the appointment, but current GE HL7 interface does not support SIU inbound to either update the Appointment Status or Cancel that appointment.  
With the use of these API's, I believe we can accomplish this.  Any guidance would be appreciated.

**Comment by jklousnitzer** [comment]
We have a similar use case in terms of needing to access the API's without a UI.  I've attempted to use password grant for token generation as you've suggested, but it doesn't look like that's supported.  I'm receiving an invalid grant: grant type must be one of authorization_code or refresh_token.

Is there any way around this to use password grant? Failing that, what does the Application Service method of authorization work? It seems to be the most suitable for this use case, but aside from listing it as an option there isn't any documentation on how to go about doing it.

**Comment by SameerSingh1991** [comment]
Grant type password is usually used for highly trusted applications and not third party applications. Service to service communication for headless applications (no UI) is not directly supported as of now.

As per us the solution to the problem you are having can be discussed on a case to case basis and may not apply to all the application. So can you tell us little bit more about the application you are trying to develop ?  What will be the workflow of your application (maybe a small happy path) ?

Few suggestions which may work in your case are 
1. If your application is not having a UI. It is possible that some other team is going to develop the UI or your application was designed to be integrated with another application which may have a UI.
 In this case you can delegate the token generation mechanism to the application which will get integrated in your headless application. You can simply take the token and forward it to the FHIR server.

2. If your app runs on a command line or in background of user's machine then you can popup a web view ( Browser like component ) which will load the FHIR server page and the user can then login to that page . When the authorization code is generated you can extract it from the web view and use it for token generation. This way you can get the token and then use it for all future FHIR interactions.

**Comment by ssinno28** [comment]
Is there a demo on how to do this? Even if a practitioner shares their credentials with us it seems like the patient would still need a profile in order to set an appointment. How do patients register in the system for Centricity if this is the case?

**Comment by ssinno28** [comment]
Hello???

**Comment by SameerSingh1991** [comment]
We don't have a demo to do this but we can help you with high level steps to achieve that using the various FHIR resources. Yes the patient will need a patient resource (which you are referring as patient profile) in FHIR server. 
Patients can be created by practitioners using the create operation of the Patient resource. 
Details available at Patient resource page in the API resources tab of dev portal ( goto https://mydata.gehealthcare.com/fhirapidoc > click on practice management APIs tab > click on Patient in left side menu ).
