### ISSUE TITLE
Updating a document with a DocumentReference PUT is requiring an ID even though an ID is passed

### ISSUE THREAD

**Issue by brspurri** [virencehealth/apiserver.virencehealth.com#31]
I recently posted a question [here](https://github.com/GEHealthcare/apiserver.gehealthcare.com/issues/28) about how to retrieve a document ID (ie., `DOC-1867581941740850`), which the wonderful people here helped me answer. 

Now that I have the `documentId` I am trying to send a `PUT` call to update the document with new information. I am running the command:

```
curl -X PUT \
  '{APISERVER}/demoAPIServer/fhir/DocumentReference/DOC-1867581941740850?_format=json' \
  -H 'Authorization: Bearer ...' \
  -H 'Content-Type: application/xml' \
  -d '<DocumentReference xmlns="http://hl7.org/fhir">
    <subject>
        <reference value="Patient/1835218576509900"/>
    </subject>
    <author>
    	<reference value="Practitioner/1225652472001060"/>
	</author>
    <type>
        <coding>
            <code value="51851-4"/>
            <display value="http://www.gehealthcare.com/fhir/cpsemr/identifiers/0/DocumentType"/>
        </coding>
        <text value="http://www.gehealthcare.com/fhir/cpsemr/identifiers/0/DocumentType"/>
    </type>
    <created value="2018-10-30T10:01:04"/>
    <description value="sample document attachment"/>
    <content>
        <attachment>
            <title value="Document-AUTO"/>
            <contentType value="text/xml" />
            <data value="BASE64_CDA_CONTENT"/>
        </attachment>
    </content>
    <context>
     <period>
            <start value="2018-10-17T12:14:00"/>
     </period>
    
        <sourcePatientInfo>
            <reference value="Patient/1835218576509900"/>
        </sourcePatientInfo>
    </context>
</DocumentReference>
'
```

Where `DOC-1867581941740850` is the documentId of the document that I am attempting to update. However, I am receiving the error: 
```
Can not update resource, resource body must contain an ID element for update (PUT) operation
```

Yet I am passing the documentID as described in the docs [here](https://mydata.gehealthcare.com/fhirapidoc). **Does anyone have any pointers on how to `PUT` to the `DocumentReference` API to update an existing document?** Specifically, how to tell the API what the document Id is?

**Comment by Torin-Shepard-GE** [comment]
I believe all you need to do is include the id element at the beginning of the body of the PUT request.
<id value="DOC-1867581941740850">

**Comment by brspurri** [comment]
Thanks for the pointer. Not sure I understand 100% though. 
I tried adding `<id value="DOC-1867581941740850" />` to the body:

```
<DocumentReference xmlns="http://hl7.org/fhir">
    <subject>
        <reference value="Patient/1835218576509900"/>
    </subject>
    <id value="DOC-1867581941740850" />
   ...
```

And I'm getting the error response:
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>BUSINESSRULE</td><td>Invalid Identifier</td></tr><tr><td>2</td><td>ERROR</td><td>BUSINESSRULE</td><td>Type is not supported by sytem</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Invalid Identifier"
        },
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Type is not supported by sytem"
        }
    ]
}
```

So it's a different error, but I can't decipher what those issue descriptions mean. Do you have any idea or pointers? I know the ID itself is a valid ID (since I got it from the headers after `POST`ing the **DocumentReference** endpoint.

**Comment by Torin-Shepard-GE** [comment]
Please check your BASE64_CDA_CONTENT.  FHIR Server performs validation on DocumentReference.content.attachment.contentType when doing a DocumentReference PUT. The beginning characters in the Base-64 encoded content must match the specified type.
When type is text/xml, the encoded document content must begin with "<?xml version="1.0" encoding="UTF-8"?>" before "<ClinicalDocument . . ."

**Comment by brspurri** [comment]
Thanks @Torin-Shepard-GE. The `BASE64_CDA_CONTENT` **is** a CDA beginning with `<ClinicalDocument ...`. The same exact payload can be passed in a `POST`, which is working ok, so I know the structure of the CDA is correct. I'm not sure if this is a problem when `PUT`ing though. I had assumed the same payload can be passed in order to update (basically overwrite in this case), but perhaps thats not the case? I can supply the full curl/postman command if needed.

**Comment by Torin-Shepard-GE** [comment]
Part of my previous comment was lost due to github markdown processing.  In a PUT request to update DocumentReference, the payload must start with text that indicates the content is XML: `<?xml version="1.0" encoding="UTF-8"?>`

**Comment by brspurri** [comment]
My CDA currently starts like this:
```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="CDA.xsl"?>
<ClinicalDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:hl7-org:v3 ../../../CDA%20R2/cda-schemas-and- 
     samples/infrastructure/cda/CDA.xsd"
     xmlns="urn:hl7-org:v3"
     xmlns:cda="urn:hl7-org:v3"
     xmlns:sdtc="urn:hl7-org:sdtc">
    ...
```

I'll try adding the encoding param by using `<?xml version="1.0" encoding="UTF-8"?>`, however, I think we're getting too far away from the problem here. My original question was about where to put the `ID` in the query/body/cda/anywhere/don't-know.

**Comment by Torin-Shepard-GE** [comment]
I believe the id can go anywhere. but I usually place it as the first element.  Unfortunately, our FHIR Server supports only id prefixes "PPA" and "PVA" and allows you to update attachments to patient registration or attachments to billing visits in the practice management side of the CPS product.  At this time we do not support using PUT to update chart documents with id prefx "DOC" in the clinical side of the product due to technical complexities related the internal storage of XML vs. non-XML documents.

**Comment by brspurri** [comment]
Ok, thank you. This helps clarify.

So, my scenario is that I am submitting a document to a patients chart via `DocumentReference` `POST` call. And at a later point, I would like to be able to update that document; however, since that doesn't appear supported, *is there a way to inactivate or delete a document* so that I could effectively, "replace" the document by inactivating/deleting, then `POST`ing a new "replacement" document? 

I don't see any `DELETE` methods for the `DocumentReference` API in the documentation.

**Is it possible to delete or inactivate a document?** The documents that I am referring are `DOC-xxxxx`.

**Comment by ychowdhary** [comment]
Thanks for posting this but currently DocumentReference delete is not supported in CPS 12.3. This is an enhancement request submitted for a future release.
