### ISSUE TITLE
Integration with centricity

### ISSUE THREAD

**Issue by AkshayaEshwar** [virencehealth/apiserver.virencehealth.com#34]
Hi,

We are trying to integrate our application with centricity. I followed this tutorial from github https://github.com/GEHealthcare/apiserver.gehealthcare.com. But getting "connection timeout error" while running the application.
![image](https://user-images.githubusercontent.com/40381112/56265528-6cd3dc80-6107-11e9-9a06-d9d0f2b21474.png)

Also followed the steps from https://mydata.gehealthcare.com/access-centricity-apis#sec3 .But it shows "failed to load page".
![image](https://user-images.githubusercontent.com/40381112/56265534-72c9bd80-6107-11e9-91a8-b469852c8614.png)
Constructed an URL based on this
 
![image](https://user-images.githubusercontent.com/40381112/56265549-7a896200-6107-11e9-99ba-ea20399dd523.png)
MyURI is -

https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://foveasso-demo.azurewebsites.net/Centricity/Redirect&aud=https%3A%2F%2Fapisandbox.gehealthcare.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2ZvdmVhc3NvLWRlbW8uYXp1cmV3ZWJzaXRlcy5uZXRcL0NlbnRyaWNpdHlcL0luZGV4IiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2ZvdmVhc3NvLWRlbW8uYXp1cmV3ZWJzaXRlcy5uZXRcL2NlbnRyaWNpdHlcL3JlZGlyZWN0Il0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4wLjEiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJjMTNlYzliZS05NTZmLTQzNDEtODAzNi05N2QyY2Y0NTNmMTkiLCJleHAiOjE4NzA2ODEzNjQsImNsaWVudF9uYW1lIjoiVGVzdEludGVncmF0aW9uQXBwIiwiaWF0IjoxNTU1MDYyMTY0LCJjb250YWN0cyI6WyJha3NoYXlhcGFyaW1hbGFkZXZpQGdtYWlsLmNvbSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.i8VJSJm6yr7H86hB29B0LC-8qVWbbmGO6dw4fzwkJURWk0ytZQh7Kz2KD2fbxT5DHc6t_aGrWEF-udfoAqGoTfPNxUd8HMYmcHOilejm7tn-nVeDfsL055ApSbfmVmL2Bqdj-bhHPSVWBbGE9G5FbSXwGkiVsKPW_0JOY-iTGA8

When I lauch this URI in browser it shows the below given page:

![image](https://user-images.githubusercontent.com/40381112/56265567-87a65100-6107-11e9-84d0-5272994052c6.png)

Please provide us some guidance to integrate.

 

Thanks,

Akshaya.A

**Comment by KedarGanta** [comment]
The Sandbox URL changed.. Please use this URL https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir

**Comment by SameerSingh1991** [comment]
@AkshayaEshwar  Can you try running our sample code (https://github.com/virencehealth/apiserver.virencehealth.com/tree/master/token-generation-sample-code) again. We have updated the new sandbox environment URL.
