### ISSUE TITLE
New Sandbox URL - https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir 

### ISSUE THREAD

**Issue by KedarGanta** [virencehealth/apiserver.virencehealth.com#35]
Developer Portal Sandbox URL has changed https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir 

Going forward, old URL will not work: https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir - DISABLED.

**Comment by joncodesalot** [comment]
Will this require changes to our Azure setup?

**Comment by KedarGanta** [comment]
I don't believe you need to update anything on your Azure.

**Comment by v152kuma** [comment]
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir ... this URL is not accessible ......I am trying to access https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata ,,,,which should be accessible to all users as per your documentation ,,,,,but cannot get the Capability Statement

**Comment by SameerSingh1991** [comment]
Hi @v152kuma 

We will be answering your issue on #45 because the same question has been asked by you in 2 different threads.
