### ISSUE TITLE
New Sandbox URL - What should be changed on our side?

### ISSUE THREAD

**Issue by joncodesalot** [virencehealth/apiserver.virencehealth.com#36]
Do I need to change anything specifically with my Azure setup due to the Sandbox URL being changed? (gehealth -> virenceaz)

I have been working with FHIR and CPS 12v3. Until the Sandbox URL changed everything had been working fine. The token I am generating is currently being rejected.  

Also, I am using the token-generation-sample-code and modified the scripts to point to the new sandbox.

Thank you.

**Comment by KedarGanta** [comment]
Only the base URL has changed. You should be able to use hwinston@sboxprovtenant.com account against this sandbox (note: you cannot use your AAD accounts to authenticate against the sandbox provided by Virence(athenahealth). We will review the sample code and update the code accordingly.

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
