### ISSUE TITLE
How to start a production OAuth Credentials // Flow

### ISSUE THREAD

**Issue by aaronrau** [virencehealth/apiserver.virencehealth.com#40]
Hi,

We were given the follow production URL

https://gehealthcarepatientaccess.b2clogin.com/gehealthcarepatientaccess.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_GEHealthcarePatientAccessSignIn&client_id= **CLIENT_ID** &nonce=defaultNonce&redirect_uri= **CLIENT_URL** &scope=openid&response_type=id_token&prompt=login

Where would obtain the correct credentials to access the production system?

Here's the screen we receive, we don't receive the GE Auth screenshot.
![Screen Shot 2019-07-16 at 2 05 43 PM](https://user-images.githubusercontent.com/207538/61329752-f06a9b80-a7d2-11e9-9df5-3305514858de.png)

Thanks,

**Comment by SameerSingh1991** [comment]
Are you trying to generate an access token from a FHIR server ? The URL you mentioned above doesn't look like a FHIR server URL.

**Comment by aaronrau** [comment]
If this doesn't look valid please provide us with the validate credentials and endpoint.

**Comment by KedarGanta** [comment]
Aaron- the above link is not a fhir server url.  This is B2C SignIn url that should be used in your patient facing app as part of patient login experience. Once the patient identity is authenticated by Microsoft B2C the response is redirected back to the url provided in the link you pasted above (normally you would want the response back to your app home page)... patient credentials should be registered with SignUp url (above is signIn) and the production fhir server url should be provided by the customers (you can use sandbox url provided in the dev portal)...

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
