### ISSUE TITLE
Searching for a given provider's appointments

### ISSUE THREAD

**Issue by anish-suki** [virencehealth/apiserver.virencehealth.com#42]
Hello,

I am trying to search appointments for a given provider. Based on the FHIR documentation I constructed this url but it doesn't return any appointments for Dr. Harry Winston in the sandbox. I tried different 'date-fromnow' condition but nothing.

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment?_format=json&_summary=true&date-fromnow=ge7||d&practitioner=1225652472001060

Does anyone has a working url for searching appointments by provider they can share?

Thanks!

**Comment by SameerSingh1991** [comment]
The following URL will give you appointments of a practitioner with date greater than 2019-07-19
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment?practitioner=1225652472001060&date=ge2019-07-19T18:30:00.000Z
Note : currently no appointments have been added so this will return zero results.

For more details related to format of passing date in search parameter of appointments API check below link
https://www.hl7.org/fhir/DSTU2/search.html#date

For more details regarding search parameters of Appointments resource you can go to the following link
https://www.hl7.org/fhir/DSTU2/appointment.html#search

**Comment by anish-suki** [comment]
Thanks! I receive the following error with the above url

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
        <title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
        <style type="text/css">
            

        </style>
    </head>
    <body>
        <div id="header">
            <h1>Server Error</h1>
        </div>
        <div id="content">
            <div class="content-container">
                <fieldset>
                    <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
                    <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
                </fieldset>
            </div>
        </div>
    </body>
</html>

**Comment by anish-suki** [comment]
Thanks. Is there a way for us to access the Centricity UI for this sandbox where we can view/create appointments, patient documents etc?

**Comment by SameerSingh1991** [comment]
As of now we do not have this facility. If you need appointments then you can check the appointments of practitioner William Bailey. 

1588761792000070 is the ID of the practitioner mentioned above.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Practitioner?given=William

Following is the URL which will give you appointments
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment?practitioner=1588761792000070

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
