### ISSUE TITLE
EHR Launch Help

### ISSUE THREAD

**Issue by mikeseale** [virencehealth/apiserver.virencehealth.com#43]
I'm looking for some details on how to use EHR Launch with CPS 12.3.  Trying to launch an application using the context of the patient that the provider is currently on within Centricity.

For example, viewing risk calculators using the patient's data that were entered during the current encounter.

I'm currently able to launch the token-generation-sample-code app within my environment, but I haven't had any luck adapting it to EHR Launch where I'm given a launch parameter to attach to my request.  Without the EHR Launch, the provider/user would need to go through the login and patient selection each time they launched the application.

**Comment by KedarGanta** [comment]
FYI - We are looking at adding the capabilities to enable EHR launch context for SMART on FHIR apps.

**Comment by mikeseale** [comment]
Thanks for the reply, Kedar!

Do expect this to be added before or after Centricity v19?

**Comment by Rinkal-jain** [comment]
this feature will be available as part of V20 GA release

**Comment by dwwinters** [comment]
@Rinkal-jain can you confirm whether EHR Launch made it into the V20 release?  Is there any documentation on this?
