### ISSUE TITLE
Functionality of the Encounter.Search FHIR API call

### ISSUE THREAD

**Issue by SameerSingh1991** [virencehealth/apiserver.virencehealth.com#44]
Please confirm the functionality of the Encounter.Search FHIR API call.  Does this call return future appointments as well as past appointments when passed in a date range that extends into the future.

**Comment by SameerSingh1991** [comment]
CPS and CEMR Encounter resources are derived from chart “documents” that record information about encounters between patients and their care providers.  Any FHIR API call on Encounter resource will return information from documents, but will not return information about appointments.  The Appointment resource should be used to get information about past and future appointments.

**Comment by jdmaple** [comment]
To clarify a bit more – we are using the Appointment resource to read future appointments.  Will the Encounter.Read call return documents from future appointments the same as past appointments?  Are there any restrictions on what is available if the appointment is in the future?

**Comment by SameerSingh1991** [comment]
Answering your question point wise :
1. we are using the Appointment resource to read future appointments.
Yes this is right you can use Appointments API call to get appointments in any date range or any other search parameter (more details available here https://smartappdocsprod.azureedge.net/appointment.html#search)

2. Will the Encounter.Read call return documents from future appointments the same as past appointments?
No, Encounter resource has a reference to only one appointment resource which means their is only one appointment linked to an encounter. You can check the Cardinality of the Appointment resource reference in Encounter resource here  https://smartappdocsprod.azureedge.net/encounter.html#resource . So in short Encounter read will not give you future or past appointments . It will only give you a reference to a linked appointment.

3. Are there any restrictions on what is available if the appointment is in the future?
If the appointment is in the future that means the medical session hasn't happened so no Encounter resource will exist for the appointment.

**Comment by jdmaple** [comment]
Good Morning - As part of our workflow, we need to get a document/notification in front of the provider _before_ the patient's appointment.  Typically, our workflow engine would process the next day's appointments the night before, generate the documents on our cloud service, and make them available to the Provider's when they arrive in the morning.   Given the answers above, can you please let us know what our options are for the following:

1. Make a document (PDF) available to the Provider so they may share it's information during the patient's visit.  This could be a chart document or encounter document or something else of your suggestion.  

2. Notify the Provider when the document is ready (through task/message/notification) and embed a link (can by copy paste if only plain text is allowed) that would allow the provider to view the document generated.

**Comment by SameerSingh1991** [comment]
I need to understand few things about your workflow engine. 

When you say "we need to get a document/notification in front of the provider" who will send this document or notification to the practitioner will your app handle this or do you want to know if FHIR server has the facility of sending notification/documents ? 

How do you plan to make the documents available to the practitioner ? through a UI in your application or something else ?

DocumentReference resource can be used to store any patient related documents.

I am trying to understand your use case/problem statement and fit in FHIR server features wherever applicable. If you can explain your application in detail we will be in a better position to suggest resources/features to use.

**Comment by jdmaple** [comment]
When the DocumentReference call is completed and a document is inserted into the patient's chart, can you confirm that the Provider will be able to see that document when the patient comes in for their visit?

We do have the ability to show the document in our UI as well.  Would this UI launch from a menu/button inside of GE?

Is there some way to trigger an Alert or Notification using the GE APIs?

**Comment by SameerSingh1991** [comment]
> When the DocumentReference call is completed and a document is inserted into the patient's chart, can you confirm that the Provider will be able to see that document when the patient comes in for their visit? 

> 

Since its a FHIR server which gives you resources. Once the DocumentReference call is completed the Provider will have access to the inserted DocumentReference resource. Since the FHIR server is not having a UI provider will only have access and not see anything.

> We do have the ability to show the document in our UI as well. Would this UI launch from a menu/button inside of GE? 

> 

When you say inside GE do you mean CPS/EMR ? Asking this because FHIR server is not having a UI so their is no question of adding a mwnu/button. 

> Is there some way to trigger an Alert or Notification using the GE APIs? 

> 

In Centricity FHIR server as of now their is no such facility.

**Comment by jdmaple** [comment]
Thank you both for your replies.  We have another question around writing a document to a patient's chart.  When we call the DocumentReference.Create 
1.) Do we need to pass in an EncounterId? (online docs are unclear on the Request Body)
2.) Are there any issues with calling DocumentReference.Create when the Encounter is in the future?
3.) Where does the document get created?  Are there any parameters that we can change/pass in to specify where it gets saved?

**Comment by SameerSingh1991** [comment]
Above question is a duplicate of #62. Closing this issue because discussion has been moved to the other issue thread.
