### ISSUE TITLE
FHIR with Local GE Centricity installation??

### ISSUE THREAD

**Issue by ssinno28** [virencehealth/apiserver.virencehealth.com#46]
Hello,

We are currently trying to integrate with a client who has an older version of Centricity and I was just wondering if these developer APIs were the same that are supported by the local desktop version of the application? They have said that they support FHIR, which I assume means we can use http and JSON to get information as well as make appointments, but it has been difficult understanding exactly how they have everything setup at the moment. Is FHIR supported by all versions of Centricity?

**Comment by SameerSingh1991** [comment]
FHIR server APIs are supported from CPS 12.3 / CEMR 9.12 on wards versions.

**Comment by ssinno28** [comment]
How do people normally use this FHIR server? we are currently using mirth connect as an integration tool which spins up a FHIR server for us, but I"m not sure how we could enable the FHIR server with centricity?

**Comment by SameerSingh1991** [comment]
You cannot enable FHIR server yourself. You need to do following 2 steps to get started with using FHIR server

1)You would get secured FHIR URL from the customer provided they have CPS 12.3 / CEMR 9.12 onwards versions.
2) Ask the customer admin to create CPS user with API server credentials  and share the username / password with you.

Once you have the FHIR server URL and a username/password you can then register your application on Centricity Developer Portal to get a client ID and client secret. You will lastly generate an access token which are used to get data from FHIR servers.
Step by step instructions on how to access resources are available on this link (https://mydata.gehealthcare.com/access-centricity-apis).

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir is a sandbox FHIR server which you can use to test and develop your applications. All examples in above link use this FHIR server. 

Once you are comfortable with generating tokens and accessing data from our sandbox FHIR server you can move on to doing same steps using your customer FHIR server.

**Comment by syam1234567** [comment]
i have the patientid and access_token. And got patient information data. plz tell me how can i update this patient info

**Comment by SameerSingh1991** [comment]
@syam1234567 It would be very helpful if you can open a different issue with a title describing your problem.

For updating a Patient resource you can use the PUT method with the patient resource in body of request. For e.g.
PUT request URL : https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/<<patient ID>>
Body will have Patient resource.
Header will have the access token.
