### ISSUE TITLE
Objects/Values not coming various endpoints.  For the Novo//CHC API Integration

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#47]
1. How do I get Language mappings (presumably out of the extensions[] array from the /Patient endpoint.  Is there mapping that needs to take place within GE Centricity for all the values before they'll come out over the API?

2. I need to be able to access "Patient Notes" from the "Additional" tab  but the /Patient API endpoint doesn't seem to support this.....

3. We're only sometimes receiving relationship information from the /RelatedPatient endpoint.
For example - 
"relationship": {
                  "coding": [
                     {
                        "system": "http://hl7.org/fhir/patient-contact-relationship",
                        "code": "parent",
                        "display": "Parent"
                     }
                  ],
                  "text": "Parent"
               },

But when "Step Father" or something like that is documented, we don't receive any information.

4.  It would be great if the /Slots endpoint returned the provider ID in addition to the location and slot information, when passing in multiple schedules that belong to multiple providers.

**Comment by Torin-Shepard-athena** [comment]
1. Language mappings come directly from a database table.  If a patient has been assigned a language, nothing more is required for the language value to be output in Patient resource.
Centricity FHIR API Server would need to be enhanced in a future release to support a way to request list of languages.

2. HL7 definition of FHIR Patient does not include any element for patient notes.  This would be an enhancement request. Centricity FHIR API Server would need to be enhanced in a future release to add an extension for patient notes in the Patient resource.

3. This refers to RelatedPerson resource.
Relationship mappings are stored in a configuration file on the Interop Server.
C:\Program Files\Centricity Practice Solution\jboss\standalone\deployments\dbnameAPIServer.war\WEB-INF\classes\com\gehcit\fhir\mappers\util\mappings.properties
PATIENTRELATIONSHIP entries in this file must be edited if any changes are made to the relationship types in CPS Administration module or EMR Setup module.
Example:  Add the following line to mappings.properties file and restart Interop Server.
PATIENTRELATIONSHIP.StepFather=STPFTH|http://hl7.org/fhir/patient-contact-relationship|Step Father
Values defined in CPS must map to this FHIR value set for relationship types.
https://smartappdocsprod.azureedge.net/valueset-relatedperson-relationshiptype.html

4. Slot.schedule is a reference to the Schedule resource that owns the Slot.
The provider ID you’re looking for comes from the Schedule Resource.
You could query Slot?searchparams&_include=Slot:schedule.
Centricity API Server does not support iterative _includes, so you would need to do another query for the Schedule resource and request _include for its referenced Practitioner.
Schedule?_id=desiredScheduleId&_include=Schedule:actor
