### ISSUE TITLE
Server error on OAuth login

### ISSUE THREAD

**Issue by jaydgus** [virencehealth/apiserver.virencehealth.com#48]
**Describe the bug**
Internal server error upon login: JBWEB000065: HTTP Status 500 - Request processing failed; nested exception is java.lang.IllegalStateException

**To Reproduce**
1. Started OAuth process with: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?response_type=code&client_id=##REDACTED##&redirect_uri=##REDACTED##&state=2d32643f-7064-4722-a480-cdb0ddfbf4e4&scope=patient%2F%2A.read%20launch%2Fpatient&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer%2Ffhir
2. Click on 'Personal account' and login with walter caldwell sample credentials
3. Error is thrown on https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize-callback

**Expected behavior**
Redirection with authorize code to our callback url.

**Screenshots**
![image](https://user-images.githubusercontent.com/3278145/62634782-15e35480-b8fc-11e9-9646-a436c863fbf2.png)

**Desktop (please complete the following information, if applicable):**
 - OS: windows 10
 - Browser: Chrome: Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by SameerSingh1991** [comment]
Is the flow working for Work account ?
