### ISSUE TITLE
Novo 2.0 project - CHC//Novo - How do I cancel an appointment via the /Appointments endpoint

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#50]
I'm currently able to create and modify appointments via POST and PUT calls, but how do I cancel an appointment?

For example - I'm attempting to PUT the following call in, by changing the "status" to "canceled" but it doesn't seem to have the desired affect.

{
      "participant": [
         {
            "actor": {
               "reference": "Patient/1009843200000000"
            }
         },
         {
            "actor": {
               "reference": "Practitioner/1625779020005680"
            },
            "type": [
               {
                  "text": "primary performer",
                  "coding": [
                     {
                        "display": "primary performer",
                        "code": "PPRF",
                        "system": "http://hl7.org/fhir/v3/ParticipationType"
                     }
                  ]
               }
            ]
         },
         {
            "actor": {
               "reference": "Location/FAC-114"
            }
         },
         {
            "actor": {
               "reference": "Practitioner/1625779020005680"
            },
            "type": [
               {
                  "text": "Resource",
                  "coding": [
                     {
                        "display": "Resource",
                        "code": "Resource",
                        "system": "http://www.gehealthcare.com/fhir/cpsemr/codesystem/PARTICIPANTTYPECPS"
                     }
                  ]
               }
            ]
         }
      ],
      "type": {
         "text": "608",
         "coding": [
            {
               "code": "608"
            }
         ]
      },
      "comment": null,
      "minutesDuration": 20,
      "end": "2019-08-05T21:00:00.000Z",
      "start": "2019-08-05T20:40:00.000Z",
      "description": "Appt Note",
      "status": "cancelled",
      "id": "9351844",
      "resourceType": "Appointment"
   }

**Comment by SameerSingh1991** [comment]
After you update the status to cancelled are you getting the updated status value on trying to GET the same appointment ?

**Comment by Torin-Shepard-athena** [comment]
It seems it is not possible to cancel appointments using the API due to an issue with one to many mappings for CPS customer-configurable appointment cancellation reasons.
It is not yet possible to map FHIR "cancelled" to a single CPS appointment cancellation choice.

**Comment by Rinkal-jain** [comment]
Appointment cancellation is addressed in v20

**Comment by royyin224** [comment]
How do I check the API version? I can cancel the appointments in dev sandbox but not in production environment.
