### ISSUE TITLE
CHC//Novo Having Issues Updating a RelatedPerson via a PUT

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#51]
Hello - 

I'm currently trying to update a RelatedPerson (specifically an Guarantor), via a PUT to the following endpoint.

PUT https://saturn.mychc1.com:9443/practicemanagertstAPIServer/fhir/RelatedPerson/G-298770_1009843200000000?_format=json

I'm pretty much using a response to craft the body of the my request:
{
    "resourceType": "RelatedPerson",
    "id": "G-298770_1009843200000000",
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/v2/0203",
                        "code": "U",
                        "display": "Unspecified Identifier"
                    }
                ],
                "text": "Unspecified Identifier"
            },
            "system": "http://www.gehealthcare.com/fhir/cpsemr/namingsystem/RelatedPersonId/1000-14224-15157042",
            "value": "G-352705_1880715390093670"
        }
    ],
    "patient": {
        "reference": "Patient/1009843200000000"
    },
    "relationship": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/patient-contact-relationship",
                "code": "guarantor",
                "display": "Guarantor"
            }
        ],
        "text": "Guarantor"
    },
    "name": {
        "family": [
            "Test 1"
        ],
        "given": [
            "Marie"
        ]
    },
    "telecom": [
        {
            "system": "phone",
            "value": "8604561234",
            "use": "mobile"
        }
    ],
    "gender": "female",
    "birthDate": "1978-09-02",
    "address": [
        {
            "line": [
                "Street"
            ],
            "city": "Hartford",
            "state": "CT",
            "postalCode": "06114"
        }
    ]
}

And I can't seem to get anything other than a 500 response. Is there something about the body that is off?

{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>FATAL</td><td>EXCEPTION</td><td>Error occured while inserting details.</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "Error occured while inserting details."
        }
    ]
}

**Comment by SameerSingh1991** [comment]
Are you able to get the above operation working on our FHIR sandbox server (https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir).

I tried updating a RelatedPerson resource on above server and it works fine. Following is the URL and payload of the request.

PUT : https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/RelatedPerson/P-262?_format=json

PAYLOAD : {"resourceType":"RelatedPerson","id":"P-262","meta":{"security":[{"system":"http://www.hl7.org/fhir/v3/Confidentiality","code":"N","display":"Normal"}]},"text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\">Suzanne Caldwell </td><td width=\"42%\">&lt;p&gt;4839 NW Montgomery St.&lt;/p&gt;&lt;p&gt;Portland, OR 97434&lt;/p&gt;&lt;p&gt;USA&lt;/p&gt;&lt;p&gt;Phone: 5035556054&lt;/p&gt;</td></tr></tbody></table></div>"},"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/RelatedPersonId/Training042","value":"P-262"}],"patient":{"reference":"Patient/1239620410000620"},"relationship":{"coding":[{"system":"http://hl7.org/fhir/v3/RoleCode","code":"WIFE","display":"wife"}],"text":"wife"},"name":{"family":["Caldwell"],"given":["Suzanne"]},"telecom":[{"system":"phone","value":"5035556054","use":"home"}],"address":[{"line":["4839 NW Montgomery St."],"city":"Portland","state":"OR","postalCode":"97434","country":"USA"}]}

Which attribute are you trying to update in RelatedPerson  ? Can you give us the version of CPS/EMR which you are using ?

**Comment by Roger-Geacom** [comment]
@SameerSingh1991  @Torin-Shepard-athena  @ychowdhary   I don't think this issue was actually resolved. The original question was for updating a guarantor RelatedPerson, the answer given is for updating a non-guarantor RelatedPerson. 

I'm also getting the same error when attempting to update a guarantor. I gett 500 with the following issue: 
```
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "Error occured while inserting details."
        }
```

Is there any workaround to update a guarantor?  There's no delete endpoint or else I would just delete and re post. The only other workaround I can think of is deleting the whole patient and reposting both, but that really is last resort solution.

**Comment by Torin-Shepard-athena** [comment]
@Roger-Geacom

RelatedPerson.id values have the form X-Y_Z where:
X = prefix indicating relationship type
P = personal contact, G = Guarantor, C = Care Team Member
Y = internal id of the related person
Z = Patient.id = PID

When using PUT RelatedPerson to update guarantor:
patient.reference must match the patient id embedded at the end of RelatedPerson.id

The following changes would have been needed in original example posted by @andylebo.
id = G-352705_1880715390093670 - should have been changed to match identifier.value
patient.reference = Patient/1880715390093670

Here is an example from our V20 API Sandbox.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient/1442678382500620?_format=json
Patient/1442678382500620 = David Parker

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/RelatedPerson?patient=1442678382500620&_format=json

RelatedPerson?patient=1442678382500620 returns Bundle with 2 resources
RelatedPerson/C-1801800684003990
RelatedPerson/G-234_1442678382500620

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/RelatedPerson/G-234_1442678382500620?_format=json
Patient.id = 1442678382500620
This patient's guarantor is RelatedPerson.id = G-234_1442678382500620

The following request will update the address for the guarantor.

PUT to https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/RelatedPerson/G-234_1442678382500620?_format=json
Authorization = Bearer {{access_token}}
Content-Type=application/json
Request Body:
``` json
{
    "resourceType": "RelatedPerson",
    "id": "G-234_1442678382500620",
    "patient": {
        "reference": "Patient/1442678382500620"
    },
    "relationship": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/patient-contact-relationship",
                "code": "guarantor",
                "display": "Guarantor"
            }
        ],
        "text": "Guarantor"
    },
    "name": {
        "family": [
            "Parker"
        ],
        "given": [
            "David"
        ],
        "suffix": [
            "Jr"
        ]
    },
    "address": [
        {
            "line": [
                "1234 Testing Place"
            ],
            "city": "Dallas",
            "state": "TX",
            "postalCode": "75022"
        }
    ]
}
```

**Comment by Roger-Geacom** [comment]
@Torin-Shepard-athena  Thanks for the response. I was able to follow the steps above and successful update the guarantor for the patient. I was also able to verify the the change occurred.  Strangely though, when I tried to update the guarantor again, following the same methodology, I get a fatal error. The only thing changed from the first time is the address.  Is there some type of update timer that's causing an issue?

**Comment by Torin-Shepard-athena** [comment]
@Roger-Geacom You revealed a bug in the RelatedPerson PUT API.

The first PUT will create a guarantor if it does not exist.  Subsequent PUT requests will be update interactions.

Our API Sandbox database content is reset nightly.  The first PUT with the above sample request body after this reset will succeed because a guarantor is created.  Further update attempts will fail due to a bug in processing the update request.
