### ISSUE TITLE
Authorization sequence fails

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#54]
Now regardless of which authorization I select (Personal or Work) it always crashes after entering user name and password:

![image](https://user-images.githubusercontent.com/1046280/66075923-9b653880-e52a-11e9-8146-add9cba69025.png)

**Comment by michelemottini** [comment]
Problem disappeared

**Comment by michelemottini** [comment]
Problem is back systematically now - I have not been able to connect successfully even once since middle of last week.

**Comment by Torin-Shepard-athena** [comment]
System was restarted.  Work account authorization flow should be working again.

**Comment by michelemottini** [comment]
No, still getting the same error.

**Comment by KedarGanta** [comment]
@michelemottini  Please try the provider and patient workflows again. If you repro the issue, please reopen the issue.
