### ISSUE TITLE
Refresh token requests fail with 'Missing redirect_uri param is required'.

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#55]
POST https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token

with a request body 

```
grant_type=refresh_token&refresh_token=xxxxx
```

fails with status code 400 and response body

```
{
    "expires_in": 0,
    "error": "invalid_request",
    "error_description": "Missing redirect_uri param is required."
}
```

According to the [OAuth2 specs](https://tools.ietf.org/html/rfc6749#section-6) refresh token requests should not include the redirect URI - not even as an optional parameter

**Comment by ychowdhary** [comment]
Thanks for bringing this to our attention.  At present time, the token endpoint requires redirect_uri when grant_type is refresh_token. This will be corrected in a future release
