### ISSUE TITLE
Invalid MIME type in DocumentReference.content.attachment.contentType

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#56]
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/DocumentReference/DOC-1551964342011100 contains:
```
                "content": [
                    {
                        "attachment": {
                            "contentType": "ASCII Text",
                            "language": "en",
                            "url": "Binary/DD-1870709606150010"
                        }
                   . . . 
                    }
                ],
  ```

but `ASCII Text` is not a valid MIME type

See specs at http://hl7.org/fhir/DSTU2/datatypes-definitions.html#Attachment.contentType

**Comment by SameerSingh1991** [comment]
Thanks for your feedback. The team is investigating and will fix these issue in our next release.
