### ISSUE TITLE
Some DocumentReference have no indexed element

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#58]
See for example https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/DocumentReference/DOC-1239739036050630

`indexed` is a required element in the base FHIR specs: http://hl7.org/fhir/DSTU2/documentreference-definitions.html#DocumentReference.indexed

**Comment by SameerSingh1991** [comment]
Thanks for your feedback. The team is investigating and will fix these issue in our next release.
