### ISSUE TITLE
Provider/Patient Permission Checking

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#61]
Our app displays a list of all appointments for a given day.  A provider is able to view that UI (it will be integrated into EMR), scroll through, and select appointments to view patient specific data.  

Are there security restrictions that need to be considered?  For example – is there an additional API call that we need to make to ensure the provider has access to view the patient they clicked?

**Comment by SameerSingh1991** [comment]
The patient resource will be available to the Practitioner only if Practitioner has access to view the details of the Patient.
So in your case when you try to get the Patient resource if the Practitioner has access he will get a response resources or else he will get zero responses as output.

**Comment by jdmaple** [comment]
When we look through the documentation for the GetPatient FHIR call, it doesn't appear that a provider ID is required.  You can see that here:
https://mydata.gehealthcare.com/fhirapidoc

What API call should we use to pass in both the PatientId and ProviderId?

**Comment by SameerSingh1991** [comment]
Yes for getting a Patient resource providerID is not required. 
The access rights checking related stuff is done in the FHIR server based on the access token which you provide. The access token contains details of the Patient or Provider logged in. Through this access token FHIR will decide whether the logged in user (which in your case is a practitioner) has access to the Patient or not.
