### ISSUE TITLE
Question on DocumentReference.Create

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#62]
When using this call we have a few questions:

1.) Are we required to pass in an EncounterId? (online docs are unclear on the Request Body)
2.) Are there any issues with calling DocumentReference.Create when the Encounter is in the future?
3.) Where does the document get created? 
4.) Are there any parameters that we can change/pass in to specify where it gets saved?

Thank you.

**Comment by SameerSingh1991** [comment]
1) While creating a DocumentReference resource encounter ID is not mandatory. Check cardinality (https://smartappdocsprod.azureedge.net/documentreference.html#resource) of the encounter resource reference in DocumentReference (https://smartappdocsprod.azureedge.net/documentreference.html#resource)

2) As per my findings FHIR documentation doesnot mention any issues with creatng DocumentReference with encounter in the future.

3) Not sure what this means ?

4) Not sure what this means ?

**Comment by SameerSingh1991** [comment]
@jdmaple When you say that "Where does the document get created?" are you asking us in which FHIR resource form it gets saved or there storage location like a database or a file system. If you can clear this out we will be in a better position to answer your 3 and 4 query.

**Comment by jdmaple** [comment]
@SameerSingh1991 -  Where will the document will be available for the provider to view? Where will they access it in the UI after we've run our process and made the DocumentReference.Create call?  

A key part of our workflow is making this document available, as part of the patient's chart, before and during the patient's appointment.

**Comment by jdmaple** [comment]
@SameerSingh1991 does my question make sense?  Can you confirm that the document created with the DocumentReference.Create call is available, as part of the patient's chart, before and during the patient's appointment?

**Comment by SameerSingh1991** [comment]
FHIR server does not have a UI of its own. It only returns resources which you need to show in the UI of your application. The document created with the DocumentReference.Create is available in the FHIR server and can be retrieved any time. 
You can through my comment (https://github.com/virencehealth/apiserver.virencehealth.com/issues/28#issuecomment-467858845) on a separate issue on how to retrieve a newly created DocumentReference resource. 
Let me know if this answers your question.

**Comment by jdmaple** [comment]
Thanks @SameerSingh1991 this was very helpful, we are 90% of the way there!

In the native Centricity UI - where will this document be available for the provider when:

1. We pass in the EncounterId to DocumentReference.Create?  Does it get created as a clinical note or something else tied to the encounter?

We want our team to understand how the EHR + FHIR API is configured when speaking to a physician using Centricity.

**Comment by jdmaple** [comment]
@SameerSingh1991 Can you point us in the right direction to find the answer to our question?

**Comment by jdmaple** [comment]
Centricity Team - @SameerSingh1991 @KedarGanta  @JonTGE @praneetlokege can you help us with the last part of our question?

**Comment by jdmaple** [comment]
@SameerSingh1991 @KedarGanta @JonTGE @praneetlokege - Can any of you please assist us with answering the remaining portion of our question?

**Comment by Torin-Shepard-athena** [comment]
DocumentReference POST requests for clinical scenarios will create new documents in a patient Chart.

DocumentReference.context.encounter is not currently used in POST requests for creation of Chart documents.  Although CPS/CEMR have an appended documents feature, this is not supported by the FHIR API Server.

[API Resources](https://mydata.athenahealth.com/fhirapidoc) explains the source for DocumentReference resource.
Content of the resource derives from the DOCUMENT table in CPS and CEMR, and the PatientProfileAttachment and PatientVisitAttachment tables in CPS.

CPS FHIR Server uses DocumentReference.context.encounter in only one use case. Patient visit attachments can be created and attached to existing visits by specifying CPS Visit ID in DocumentReference.context.encounter.  This element is ignored in all other scenarios.

**Comment by Amits2070** [comment]
As this issue has been responded and it is pending with customer.
Closing this issue for now.
