### ISSUE TITLE
Novo 2.0 project - CHC//Novo- Sporadically losing refresh token - having to log in again to obtain new Auth Code

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#63]
Hello - 

This should probably get routed to Torin Shepard as we've been working with him on the CHC/Novo/Redox install. We're planning on logging this ticket and forwarding along to him via email.

We're were previously running into issues with states getting inappropriately cached.  CHC has since switched to a newer version of GE, where we appear to be running into this issue less (we did run into it this morning (10/15/2019) - but tried to log-in an hour later and were successful.

Over the last two days, each morning, our refresh token appears to have failed, and we've been forced to log-in again.  We're looking to review the logs to help identify why this may be happening, as this won't be great in Production.

As a reminder from previous emails where we left of:
===========
This is a difficult issue.  See below for an explanation about next step to gather more information.
 
Please have Waqar change the FHIR Server logging level from DEBUG to TRACE and restart JBoss.
 
The API Server authorize endpoint shows a user type selection page with the Work account button. This button is a link to login.microsoftonline.com.
 
Note, the state requested by Redox is kept internally in memory in the FHIR Server, and a different state is passed to AAD.  I now understand this is intentional and done by design.
 
The link to log into AAD is designed to have a different state value each time.
 
Unfortunately, the CHC FHIR API server seems to be stuck in a state where the authorize endpoint always generates the same AAD login URL with the exact same state value.
https://login.microsoftonline.com/a77a72fc-fc4c-4caa-9c3c-7b3c540c888a/oauth2/authorize?...&state=1ab25c95-b59f-4419-8116-924daaae2646&...
 
The authorization state is maintained for 10 minutes maximum for security purposes.  User is not allowed to take longer than 10 minutes to enter their account credentials in AAD.
 
I believe you are seeing invalid request because state=1ab25c95-b59f-4419-8116-924daaae2646 is expired, but have yet to understand why CHC API Server continues to generate this same expired value when creating the AAD login URL.
 
I request the following as the next step.
 
Can Waqar please change the FHIR Server logging level from DEBUG to TRACE and restart JBoss to get more information about cache and learn if JBoss restart has any affect.
 
.....\jboss\standalone\deployments\practicemanagertstnameAPIServer.war\WEB-INF\classes\log4j2.xml
Go to bottom of file.
Change /Configuration/Loggers/Root element to TRACE: <Root level="TRACE">
Restart JBoss to make sure API Server uses trace level logging.
 
Then Andrew can repeat the attempt to use the practicemanagertstAPIServer/oauth2/authorize call and find out if Work account button will have a different state value in the AAD login URL.
 
If the API Server authorize-callback still returns invalid request, I’m hoping CentricityFHIR.log would then have additional information about API Server storing authorization state information in the internal in-memory and JDBC caches.
 
From: Andrew Lebovsky <andy.lebovsky@redoxengine.com> 
Sent: Monday, August 26, 2019 11:11 AM
To: Torin Shepard <tshepard@athenahealth.com>; Khokhar, Waqar <khokhaw@chc1.com>; Rozanski, Lori <RozansL@chc1.com>; Kedar Ganta <rganta@athenahealth.com>
Cc: Puttajunjaiah Krishnamurthy <pkrishnamurthy@athenahealth.com>; Rashmi MS <rms@athenahealth.com>; Philips, Tyler <philipt@chc1.com>; 'lewis@redoxengine.com' <lewis@redoxengine.com>; Capreol, Grace <grace@chc1.com>; 'joseph.gordon@pointclearsolutions.com' <joseph.gordon@pointclearsolutions.com>; Edward Pfeiffer <epfeifferjr@athenahealth.com>; Bianco, Edward <biancoe@chc1.com>; Ciaburri, Nicholas <CiaburN@chc1.com>; 'Shawn Ewing' <shawn.ewing@pointclearsolutions.com>
Subject: Re: Centricity/ Redox - Invalid Authorization Request
 
**Logs from last week attached ^^
 
Login URL –
https://saturn.mychc1.com:9443/practicemanagertstAPIServer/oauth2/authorize?response_type=code%20id_token&scope=openid%20profile%20user%2F*.*%20offline_access&redirect_uri=https%3A%2F%2Fcandi.redoxengine.com%2Foauth&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Rhc2hib2FyZC5yZWRveGVuZ2luZS5jb20iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvYXBwLnJlZG94ZW5naW5lLmNvbVwvb2F1dGgiLCJodHRwczpcL1wvZGFzaGJvYXJkLnJlZG94ZW5naW5lLmNvbVwvb2F1dGgiLCJodHRwczpcL1wvY2FuZGkucmVkb3hlbmdpbmUuY29tXC9vYXV0aCJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJmOTIxNzAwYi04YzhhLTQzNWUtYTFlNi01MjE0N2M2YmQwODMiLCJleHAiOjE4NzkzODI1OTksImNsaWVudF9uYW1lIjoiQW5vdGhlciBGaW5hbCBDSEMgLSBQbGF5Z3JvdW5kIiwiaWF0IjoxNTYzNzYzMzk5LCJjb250YWN0cyI6WyJhbmR5LmxlYm92c2t5QHJlZG94ZW5naW5lLmNvbSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.KMer5IgH8sHm-J4AwnWqxdzQmxNVCAA1KCQLgruLu4bHVoBzE_416H7ZHrs3GuQnBrF9K3_MR55Emi_EuZe-pFABHIbsWPvQy0H82BHG2Lfup7QnV3PtrKqv_nCAHUELVgBMCyUViySOGJ6WGjHBAd3gkfWX43qWbkFcHBS5Sdo&state=97cdcc46-88cd-4a5e-8e47-e56fc3ec238a&aud=https%3A%2F%2Fsaturn.mychc1.com%3A9443%2FpracticemanagertstAPIServer
 
After hitting Login button:
https://login.microsoftonline.com/a77a72fc-fc4c-4caa-9c3c-7b3c540c888a/oauth2/authorize?response_mode=form_post&prompt=login&client_id=884f28d8-0361-4056-b869-5f381c9d4986&response_type=code+id_token&redirect_uri=https%3A%2F%2Fsaturn.mychc1.com%3A9443%2FpracticemanagertstAPIServer%2Foauth2%2Fauthorize-callback&resource=884f28d8-0361-4056-b869-5f381c9d4986&state=1ab25c95-b59f-4419-8116-924daaae2646&scope=openid%20profile%20user/*.*%20offline_access&nonce=8a462e62-b56d-4a0b-98b9-9b6e9f91cab9
 
After entering email:
https://login.microsoftonline.com/a77a72fc-fc4c-4caa-9c3c-7b3c540c888a/oauth2/authorize?response_mode=form_post&prompt=login&client_id=884f28d8-0361-4056-b869-5f381c9d4986&response_type=code+id_token&redirect_uri=https%3A%2F%2Fsaturn.mychc1.com%3A9443%2FpracticemanagertstAPIServer%2Foauth2%2Fauthorize-callback&resource=884f28d8-0361-4056-b869-5f381c9d4986&state=1ab25c95-b59f-4419-8116-924daaae2646&scope=openid%20profile%20user/*.*%20offline_access&nonce=8a462e62-b56d-4a0b-98b9-9b6e9f91cab9

**Comment by Torin-Shepard-athena** [comment]
This is a difficult issue to find root cause.  The most recent API debug logs from CHC help, but to gather more information, we will probably need to deploy one or more additional class files into the CHC API Server with additional logging to get more information about use of security tokens.

**Comment by Torin-Shepard-athena** [comment]
Provided dedicated patch to CHC CPS FHIR API Server with additional logging that made it possible to determine Redox app was not sending accessTokens in some API requests.  Redox made changes to resolve the issue in December 2019.
