### ISSUE TITLE
CHC//Novo Install - Unlinking RelatedPersons to Patients

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#64]
How do I unlink a patient and a RelatedPerson?

The Novo Application is planning on allowing users to update a patient's contacts (RelatedPersons over the API).

I know that the link from RelatedPerson to the patient lives in the RelatedPerson record:
"patient": {
                    "reference": "Patient/1009843200000000"
                },

But it doesn't look to be possible to send a PUT in with this field as Null, or non-existent to unlink the two.

Is this possible over the API?

======

Same question for a RelatedPerson with a type of Guarantor?

**Comment by Torin-Shepard-athena** [comment]
Unlinking RelatedPersons from Patients is not yet supported through the API.

**Comment by Rinkal-jain** [comment]
This functionality is not currently supported and may be considered for a future release but is not yet planned.
