### ISSUE TITLE
Novo 2.0 project - CHC//Novo - RelatedPersons contacts not coming out over the API.

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#67]
Hello - 

I'm making several /RelatedPersons calls, and certain relationships that are defined defined on the RelatedPerson (such as Foster Parent, or Step Parent) aren't coming out over the API.

In working with CHC, we're pretty sure there's a flatfile that needs to be updated, but we're not having any luck with any edits we try.

We've tried the following:
![image](https://user-images.githubusercontent.com/20426558/67772456-16d1e100-fa28-11e9-9eba-9332a56bde34.png)
![image](https://user-images.githubusercontent.com/20426558/67772481-1fc2b280-fa28-11e9-994d-9d8ea80841f0.png)

**Comment by Torin-Shepard-athena** [comment]
jboss\standalone\deployments\dbnameAPIServer.war\WEB-INF\classes\com\gehcit\fhir\mappers\util\mappings.properties file
These mappings have the following format.
MAPPINGTABLENAME.code=FHIR code|FHIR system|FHIR display name[|CPS/EMR Display Name]

The ".code" value must match the value defined in CPS Administration Orange folders > Registration > Contact Relationship or Patient Relationship
**Spaces must be "escaped" with the backslash character.**

`PATIENTRELATIONSHIP.Power\ of\ Attorney=POWATT|http://hl7.org/fhir/RoleCode|power of attorney`

You must restart JBoss on Interop server to force Centricity API Server to read the modified mappings.properties file.

**Comment by andylebo** [comment]
In CPS v12 - there are two copies of the mapping file within the setup.
There should be another file that should be updated starting in v12.

**Comment by GaryHammer701** [comment]
@andylebo   Can you tell me which folders contained the mapping files that had to be updated?  I'm trying to work on a knowledge article for the athenahealth support team.

**Comment by andylebo** [comment]
Hi @GaryHammer701 - I'm actually from the outside system sending the information into GE. @Torin-Shepard-athena is actually going to be on the phone with Natalia from the health system on Friday trying to correct the appropriate files.  I imagine he'll be able to get you the names of the folders that need to be updated.

**Comment by Torin-Shepard-athena** [comment]
jboss\standalone\deployments\mappings.properties file an be updated with proper PATIENTRELATIOHSHIP entries to match the relationship types defined in CPS Admin module.  This was completed at CHC on February 14.
