### ISSUE TITLE
Sandbox down?

### ISSUE THREAD

**Issue by JayJMobley** [virencehealth/apiserver.virencehealth.com#68]
Is the sandbox at https://cpsapisandbox.virenceaz.com:9443/demoAPIServer down?

**Comment by KedarGanta** [comment]
I can access the sandbox. 

Quick test: Check the metadata https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata

**Comment by sriramanvellingiri** [comment]
@KedarGanta 

Can you please check the sandbox is working? Based on the documentation when I tried to generate the OAuth token and it returns 500 internal server error. Pasting the request and response for your reference.

URL: https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token
METHOD: POST
Request parameter : Basic Auth(Username : client id and password :client secret ) and  body parameters (grant_type:authorization_code,redirect_uri:<redirect_uri>, code:<code> )
Response Parameter : {
    "expires_in": 0,
    "error": "invalid_client",
    "error_description": "An unexpected error has occurred. Please try this operation again later."
}

As per @JayJMobley post , the Server Url  https://cpsapisandbox.virenceaz.com:9443/demoAPIServer  is still returning 404?

**Comment by KedarGanta** [comment]
Hello @JayJMobley  @sriramanvellingiri  Yes, I am able to generate the token.  were you able to follow the instructions from dev portal and get the appropriate auth code after selecting the patient? Are you trying provider flow or patient flow?

![image](https://user-images.githubusercontent.com/37341248/69397911-d8cd8300-0c9c-11ea-8be9-58bf5e5a0d43.png)

**Comment by sriramanvellingiri** [comment]
Thanks @KedarGanta for the response.

Yes i m following the instructions from the dev portal(https://mydata.gehealthcare.com/access-centricity-apis).

I am trying the provider portal and can able to get the auth code after selecting the patient. Still i m getting the below errror for your reference. Comparing with your screen shot it seems the header infromation differs and can you please help on troubleshooting this issue ?

![untitled (2)](https://user-images.githubusercontent.com/11173747/69514695-30f0d780-0f72-11ea-82db-6748b475fef1.png)

**Comment by KedarGanta** [comment]
@JayJMobley  @sriramanvellingiri   We are not able to recreate this issue. Please check the client id that was generated in your developer portal account. 
I am closing the issue. If you are still experiencing the issue, please log a different issue.
