### ISSUE TITLE
CPS 19 - FHIR - Observation Write

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#69]
Do I need to call Observation.Read to get SDID for each clinical history items (Observation Term) for Observation.Write calls ? 

If so then if I need to update 50 clinical history (Observation Term) then I need to call 50 calls to Observation.Read to get SDIDs then 50 Observation.Write calls so total 100 calls.

Is there a better way to minimize APIs calls to update Observation Terms in one go?

Kind Regards,
Sangkar

**Comment by mikeseale** [comment]
SDID is the document's ID, so all of the 50 obs terms would have the same SDID if you are writing them to one patient's document.

**Comment by Torin-Shepard-athena** [comment]
@mikeseale is correct.  You can pass in a Bundle of multiple Observations to write values for multiple OBS terms in a single Observation.Write call.

@sangkars The question was not clear.  Was "clinical history items (Observation Term)" asking about how proper way to get values needed for Observation.code.coding for various OBS terms?

You can query ValueSet?name=CQMCODE to get cpsemr OBS term codes and LOINC codes that can be used to write Observations.

**Comment by saikumarreddy1994** [comment]
![image](https://user-images.githubusercontent.com/44068822/68581611-c3877600-049e-11ea-8a0b-20cdb627f005.png)

@Torin-Shepard-athena  , thanks for your reply. When we tried passing multiple observations in a bundle. We get Failed Response as "Expected observation but found bundle".
Attached the screenshot of same.

**Comment by Torin-Shepard-athena** [comment]
When you post a Bundle, please remove the resource type from the URL.  Post to https://hostname_or_ip_address:9443/dbnameAPIServer/fhir/

**Comment by saikumarreddy1994** [comment]
Thanks, Its working fine.

**Comment by Torin-Shepard-athena** [comment]
Closing issue as resolve.  Please reopen if there are any more concerns.
