### ISSUE TITLE
CPS 19 - FHIR - PostPayment

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#70]
Does "../fhir/$PostPayment" support copay amount posting for the current/same day appointment ? 
If yes then does it do Visit ID creation internally in CPS ?
Does it support payment posting for Patient Balance collection ? If so then how?

Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by Rinkal-jain** [comment]
Support for some of the newer financial resources may be considered for a future release but is not yet planned.
