### ISSUE TITLE
CPS 19 - FHIR - AllergyIntolerance.write

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#73]
Is AllergyIntolerance.write in future road map? 
If so then when will it be available tentative ? All our CPS customers need this.
Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
This is not yet supported. It may be considered for a future release.
