### ISSUE TITLE
CPS 19 - FHIR - DocumentReference.write

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#74]
DocumentReference.write (PDF is supported to Registration module but I noticed only RTF is supported as clinical document which saves to CPS database). 
Is the way to send clinical document as PDF in future release which saves in CPS database?
Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
PDF format is not supported for Chart documents.  You can use DocumentReference.content.attachment.url to create PDFs as external attachments to Chart documents.
