### ISSUE TITLE
CPS 19 - FHIR - patient Pharmacy update

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#77]
Does patient pharmacy details update available or is this in future road map?
Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
Pharmacy contacts are not yet supported in the RelatedPerson resource.  This may be considered for a future release.

**Comment by Rinkal-jain** [comment]
This functionality is not currently supported and may be considered for a future release but is not yet planned.
