### ISSUE TITLE
CPS 19 - FHIR - patient Employer update

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#78]
Does patient's employer details update available or is this in future road map?

Kind Regards,
Sangkar

**Comment by sangkars** [comment]
> e

**Comment by sangkars** [comment]
Does patient's employer details update available or is this in future road map?

Kind Regards,
Sangkar

**Comment by Torin-Shepard-athena** [comment]
The answer is in the API [Documentation](https://mydata.gehealthcare.com/fhirapidoc).
Look at the page for Organization resource.
Source section shows this is a system resource type and it includes employers.
Supported operations show this resource type currently supports only Read and does not support Create or Update.

You can also get the same information by looking at the [Conformance Statement](https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata) for the API Server.  Look at interactions supported for Organization resource.

**Comment by saikumarreddy1994** [comment]
Any updates  of future RoadMap ??

**Comment by rohanchavancr** [comment]
Employers as patient contacts are not yet supported in RelatedPerson resource.  This is not yet planned for a future release which will require FHIR STU3 and /or R4 to be able to indicate the employer as relationship type.
