### ISSUE TITLE
CPS 19 - FHIR - patient Account Statement

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#79]
Is there any possible way to retrieve patient statement from FHIR? or is this in future road map?
Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
FHIR DSTU2 does not support information needed for patient statement.  FHIR STU3 and R4 have better support for financial resource types.  Support for some of the newer financial resources may be considered for a future release but is not yet planned.
