### ISSUE TITLE
CPS 19 - FHIR - patient Insurance read

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#80]
Does additional information like patient relationship, patient guarantor for insurance is available in FHIR? or is this in future road map?

Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
CPS/CEMR API Server has some support for guarantor using RelatedPerson resource.  See comment posted for issue 66 about factors that must be considered before supporting insured party other than the patient being the insured person.
https://github.com/virencehealth/apiserver.virencehealth.com/issues/66#issuecomment-546133998

**Comment by ychowdhary** [comment]
Please reopen if you still encounter this issue.
