### ISSUE TITLE
CPS 19 - FHIR - patient Registration document authorization write

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#81]
Does registration document authorization write available in FHIR? or is this in future road map?
Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
This is not supported in CEMR, but is supported in CPS.  CPS DocumentReference resource supports create for registration documents as attachments to patient registration stored in PatientProfileAttachment table in CPS database.
