### ISSUE TITLE
CPS 19 - FHIR - patient's Pharmacy read

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#84]
Is it possible to get patient's Pharmacy details through FHIR ? or is this in future road map?

Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by rohanchavancr** [comment]
[Pharmacy contacts are not yet supported in the RelatedPerson resource. This may be considered for a future release.](url)

**Comment by rohanchavancr** [comment]
Pharmacy contacts are not yet supported in the RelatedPerson resource. This may be considered for a future release.

**Comment by Amits2070** [comment]
A new bug has been created for this issue . it will be addressed in further released. 
closing this issue.
