### ISSUE TITLE
Novo 2.0 project - CHC//Novo - Email Address isn't coming out via RelatedPersons endpoint

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#85]
Hello - 

Seems like this should be possible via the specs - but we're not receiving the email address for GET/RelatedPersons.
I'd expect it to be within the Telecom array - 
 "telecom": [
                  {
                     "system": "phone",
                     "value": "3333333333",
                     "use": "mobile"
                  }
               ],

Furthermore, if we try to send in an email on a PUT /RelatedPersons - 
Here's the error response:
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>FATAL</td><td>EXCEPTION</td><td>Database error occured while inserting data</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "Database error occured while inserting data"
        }
    ]
}

**Comment by Torin-Shepard-athena** [comment]
The "specs" show that email is not mapped.
[API Resource Definitions](https://mydata.gehealthcare.com/fhirapidoc)
Activate/Navigate to page for RelatedPerson.
Scroll down to Mappings.
[Related Person Mappings](https://mydata.gehealthcare.com/static/apidoc/ig-ge-relatedperson.html#mappings)
email is not listed as being mapped as one of the telecom elements.

This is a reasonable enhancement request.

**Comment by ychowdhary** [comment]
Thanks for posting the issue. We realize that we have an issue in our product. We will fix this issue in our next release i.e. support the Email Address in RelatedPerson.
