### ISSUE TITLE
Centricity

### ISSUE THREAD

**Issue by syam1234567** [virencehealth/apiserver.virencehealth.com#86]
I am new to Centricity.So i don't have much experience with centricity. I can able to generate the access token and  patientid 
 "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkJCOENlRlZxeWFHc................dd2776d4ad11d3c916f40152859296a"

patient=1442678386450620

using these i can also GET patient details 
this is the URL i used: 
url : https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/1442678386450620
How do i Update, Delete Patient Details.PLZ help me

I have shared the scrren shot of patient details below

![ccccccccccc](https://user-images.githubusercontent.com/55385519/68765252-5ad8fe80-0642-11ea-9b83-9ac332443e97.png)

**Comment by Torin-Shepard-athena** [comment]
HL7 FHIR RESTful API at http://hl7.org/fhir/DSTU2/http.html describes HTTP requests that should be used for read, create, update, and other operations.
read = GET, create = POST, update = PUT, delete = DELETE
The request body must contain the valid FHIR resource for create and update operations.
"Pretty" shows only the narrative from the text element of the FHIR resource.
Format the read = GET response body as "Pretty" or "Raw" to see the XML resource content.
Please review documentation for each FHIR resource type at https://mydata.gehealthcare.com/fhirapidoc.
Delete operation is supported for only a few resource types, but is _**NOT**_ yet supported for Patient resource.
The Conformance statement indicates which operations are supported for earch resource type.
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata

**Comment by syam1234567** [comment]
When I try to UPDATE, I am getting not authorized . 
 this is my UPDATE API
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/1306944512000610

**Comment by Torin-Shepard-athena** [comment]
The sample calls to authorize endpoint listed in the [API Access Documentation](https://mydata.gehealthcare.com/access-centricity-apis) specifiy OAuth2 scopes for only patient/*.read.  You must call the authorization endpoint with a "write" scope to be able to perform create, update, delete operations.

[SMART App Launch: Scopes and Launch Context](http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context/index.html) describes the supported scopes.

Please confirm your requested scope includes Patient.write when you call the authorize endpoint.  You can also examine the response from the token endpoint to confirm the access token(s) you get include Patient.write scope.

**Comment by syam1234567** [comment]
I tried to UPDATE but i am getting error
the error says this:  <td>Incorrect Content-Type header value of "application/x-www-form-urlencoded" was provided in the request. A FHIR Content-Type is required for "UPDATE" operation</td>
this is my API:  PUT https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/1886253898137440

**Comment by Torin-Shepard-athena** [comment]
Try Content-Types as application/xml and application/json depending on the format you are using in the request body.
http://hl7.org/fhir/dstu2/http.html#mime-type has information about FHIR content types.

**Comment by syam1234567** [comment]
Guys, thank you for the help . And i need one more.

when i try to access work account it asks for Microsoft sign up. can i aviod it, if not, then how can i generate  "CODE" . Because i need to build an App there showing that sign may not be good.

Please Help

**Comment by Torin-Shepard-athena** [comment]
https://mydata.athenahealth.com/access-centricity-apis
"Provider workflow: Generate authorization code using Work account" mentions the information you need. If you are using sandbox for testing, you can use our sample provider login credentials,  See this page on our developer portal for the credentials.

**Comment by ychowdhary** [comment]
Please reopen if you still encounter this issue.
