### ISSUE TITLE
Pre-population of link

### ISSUE THREAD

**Issue by shahamitj** [virencehealth/apiserver.virencehealth.com#87]
When launching the web browser from Centricity for the provider login, is it possible to prepopulate email and patient id so that it's pre-entered/selected to reduce the number of clicks? Additionally, once the user has authenticated once, is it possible to keep that user logged in?

This information is not available in the `Constructing the Access My Data URL` in the webpage
https://mydata.gehealthcare.com/access-centricity-apis

Thanks!

**Comment by SameerSingh1991** [comment]
It is not possible to prepopulate email and patient ID.
You can keep the user logged in by using the refresh_token to get new access token every time it expires.
Please go through this issue to know how to generate refresh token #38

**Comment by mikeseale** [comment]
To add to this, there is a Launch type designed by FHIR for the use case described by @shahamitj called "EHR Launch" that should send the scope and context of where the provider is within Centricity without having to log back in.  Per @KedarGanta, this has not been implemented within Centricity's FHIR API yet.
