### ISSUE TITLE
Claim and CPT level patient balance details

### ISSUE THREAD

**Issue by Healthipas** [virencehealth/apiserver.virencehealth.com#89]
Hi All,
Is there any API that gives the claim and CPT details?

We are not able to find the Encounter level patient balance details like Patient Paid, Insurance Paid, Insurance Adjustment etc with the individual level cpt codes and description. Attaching the grid on how it looks like:
![image058](https://user-images.githubusercontent.com/57922143/69098600-8a12b580-0a1e-11ea-9548-d32b50135f45.jpg)

**Comment by Rinkal-jain** [comment]
Support for some of the newer financial resources may be considered for a future release but is not yet planned.
