### ISSUE TITLE
Payment posting batches

### ISSUE THREAD

**Issue by Healthipas** [virencehealth/apiserver.virencehealth.com#90]
How to send payments to the existing batch?
If we create a new batch, how can we get the batch id and batch name, so we can use that existing batch to send payments to?
Is there a separate API call that will give us all the available batches in the CPS?
 
Example: Under the Practice Management APIs, I see that there is an API called “Posting (CPS only)” which will return the batch id in the response. I’m getting an error while making a call to this API.
 
GET [base]/fhir/$Account?{search parameters}{&_format=[json|xml]&_summary=[true|data]}

 
Any idea on what to pass in the search parameters above to get the batch id? Currently, I’m passing the below request and it’s failing
 
Request:
 
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/$Account?BatchName|rv
 
Response:
 
“Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[$Account] with parameters [[BatchName|rv]]”

**Comment by Rinkal-jain** [comment]
Support for some of the newer financial resources may be considered for a future release but is not yet planned.
