### ISSUE TITLE
PatientUpdate for Race and Ethnicity not updating for few items

### ISSUE THREAD

**Issue by saikumarreddy1994** [virencehealth/apiserver.virencehealth.com#92]
Few of the items for Race(stateprohibited,patientdecline etc..,) and Ethnicity(stateprohibited,patientdecline etc..,) are not getting posted even though we are getting the code,display value from fhir.valueset api.
![image (1)](https://user-images.githubusercontent.com/44068822/69229682-e7883d00-0bab-11ea-9978-cd6140ea51c5.png)

**Comment by Torin-Shepard-athena** [comment]
Please see [Issue 101](https://github.com/virencehealth/apiserver.virencehealth.com/issues/101).
The HL7 code mappings are not set in the default demonstration database used in the API Sandbox.
