### ISSUE TITLE
Practitioner - Concept of Roles, Groups etc?

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#94]
We need the ability to provide or restrict access to our app via some permission mechanism.  
How is this concept implemented in Centricity and is it exposed through the APIs? 

For example - is there the concept of Roles, Security Groups, Departments etc that a provider is assigned to?  Can we view such a group in the API and use it to filter providers?

**Comment by KedarGanta** [comment]
@jdmaple Yes, users of your app should have appropriate roles in Centricity.

In Centricity, under Admin > Users >  User Management > Open User account > Select Security tab >  Select 'API Server User' group >Under Permission List, select the appropriate access.

**Comment by ychowdhary** [comment]
Please reopen if you still encounter this issue.
