### ISSUE TITLE
Novo 2.0 project - CHC//Novo - Missing PhoneNumbers from /Patient endpoint

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#95]
**Description**
/Patient endpoint isn't returning all the phonenumbers on file for a patient.  If the same type is on file multiple times (i.e multiple Home or Mobile phones, only the first is returned))
Specifically looking at the Telecom Array - 

"telecom": [
            {
               "system": "phone",
               "value": "2222222222",
               "use": "home"
            }
         ],

**Expected behavior**
I should be able to see all phonenumbers

**Screenshots**
![image](https://user-images.githubusercontent.com/20426558/71018476-2b446880-20be-11ea-82b2-e8f20100e5bb.png)

**Comment by Torin-Shepard-athena** [comment]
This is good feedback.  Current implementation of Patient resource will output multiple phone numbers if they have different phone types, but does not output multiples for a single phone type.  Enhancement to CPS FHIR Server would be required to support this.

**Comment by Torin-Shepard-athena** [comment]
Related Question: Knowing that it is not yet possible to GET all the phone numbers on file –

How do I PUT /Patient back in (to make other demographics updates) such that I don’t clear out the phone numbers on file?

I’ve tried several combinations such as
"telecom": [
            {
               "use": "mobile",
               "value": null,
               "system": "phone"
            },

Or not sending the telcom Array, or sending an empty telecom array ->

It appears that the phone numbers that I don’t send get cleared out.

**Comment by Torin-Shepard-athena** [comment]
Enhancement request put into the system for future release.
