### ISSUE TITLE
Novo 2.0 project  - CHC//Novo - PUT /Patient seems to create a guarantor regardless of body

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#96]
Everytime we PUT /Patient to update an existing patient, we appear to be creating a new guarantor.

**To Reproduce**
Within the Extension array of the patient, here are the fields currently on file with the patient
{
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
               "valueBoolean": true
            },
            {
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
               "valueReference": {
                  "reference": "RelatedPerson/G-370383_1889775163729800"
               }
            },

Then we do a **PUT**
PUT - https://mercury.mychc1.com:8443/practicemanagerAPIServer/fhir/Patient/1889775163729800?_format=json
**Body:**
{
         "extension": [
            {
               "valueCodeableConcept": {
                  "coding": [
                     {
                        "display": "Abenaki",
                        "code": "1006-6",
                        "system": "http://hl7.org/fhir/v3/Race"
                     }
                  ]
               },
               "url": "http://hl7.org/fhir/StructureDefinition/us-core-race"
            },
            {
               "valueCodeableConcept": {
                  "coding": [
                     {
                        "display": "Andalusian",
                        "code": "2138-6",
                        "system": "http://hl7.org/fhir/v3/Ethnicity"
                     }
                  ]
               },
               "url": "http://hl7.org/fhir/StructureDefinition/us-core-ethnicity"
            },
            {
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
               "valueBoolean": true
            },
            {
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
               "valueReference": {
                  "reference": "RelatedPerson/G-370383_1889775163729800"
               }
            }
         ],
         "careProvider": [],
         "communication": [
            {
               "language": {
                  "coding": [
                     {
                        "system": "urn:ietfbcp:47",
                        "code": "ach",
                        "display": "Acoli"
                     }
                  ],
                  "text": "Acoli",
                  "preferred": true
               }
            }
         ],
         "identifier": [
            {
               "type": {
                  "coding": [
                     {
                        "system": "http://hl7.org/fhir/v2/0203",
                        "code": "PI"
                     }
                  ]
               },
               "system": "http://www.gehealthcare.com/fhir/cpsemr/namingsystem/PatientId/1000-14224-1692042",
               "value": "527622"
            },
            {
               "value": null,
               "system": "http://hl7.org/fhir/sid/us-ssn",
               "type": {
                  "coding": [
                     {
                        "code": "SB",
                        "system": "http://hl7.org/fhir/identifier-type"
                     }
                  ]
               },
               "use": "secondary"
            }
         ],
         "address": [
            {
               "country": null,
               "postalCode": "22222",
               "state": "TN",
               "city": "asdfasdf",
               "line": [
                  "asdfasdf"
               ]
            }
         ],
         "gender": "male",
         "birthDate": "1976-10-18",
         "telecom": [
            {
               "use": "home",
               "value": null,
               "system": "phone"
            },
            {
               "use": "mobile",
               "value": null,
               "system": "phone"
            },
            {
               "use": "work",
               "value": null,
               "system": "phone"
            },
            {
               "value": null,
               "system": "email"
            }
         ],
         "name": [
            {
               "given": [
                  "J12",
                  "M13"
               ],
               "family": [
                  "G12"
               ],
               "use": "official"
            },
            {
               "given": [
                  "J12"
               ],
               "use": "nickname"
            }
         ],
         "id": "1889775163729800",
         "active": true,
         "resourceType": "Patient"
      }

Then - if I do a GET /Patient, it looks like we're creating a new "G-370384" ID - 
{
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
               "valueBoolean": true
            },
            {
               "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
               "valueReference": {
                  "reference": "RelatedPerson/**G-370384**_1889775163729800"
               }
            },

**Expected behavior**
I'd expect to not be changing the guarantor linkage if we pass in the same value that we receive.

**Comment by Rinkal-jain** [comment]
This functionality is not currently supported and may be considered for a future release but is not yet planned.
