### ISSUE TITLE
Patient 'Cellular' phone numbers not being retrieved in Appointment or Patient GET API requests

### ISSUE THREAD

**Issue by apjardim3** [virencehealth/apiserver.virencehealth.com#98]
How do we get the patients' phone type of 'Cellular' in the API response data?

In our requests to retrieve Appointments and Patients, we receive all of the <telecom> types EXCEPT the phone numbers that have a type of 'Cellular'.  All other phonetypes are delivered in the response structure (Home, Work, Fax and Pager).  

Is there a config setting that we are missing in our API request or in the actual CPS system that needs to be set in order for the 'Cellular' phone types to be passed in the response?

Any help on this would be greatly appreciated; please advise.

**Comment by Torin-Shepard-athena** [comment]
Thanks for posting the issue. We realize that we have an issue in our product. We will fix this issue in our next release i.e. support the 'Cellular' phone type in the API.  Until then, we suggest that you use phone type 'Mobile'.

**Comment by apjardim3** [comment]
Thanks for confirming the issue.  When can we expect the fix in the next 'release'?  We will need to communicate this to our customers and figure out if we need to go through a data conversion process to migrate their 'Cellular' phone types to 'Mobile' or wait until the next release.

**Comment by Torin-Shepard-athena** [comment]
The issue will be fixed in the V20 release.

**Comment by kdevine** [comment]
This has not been fixed.  I have a client using V22 and it does not show Cellular, nor is this supported in the PUT operation for telecom.  It shows all "Cellular" as "mobile", but Mobile is a different option in the dropdown.
